### PR TITLE
Resolve #1089 -- Path traversal for Content path

### LINKED ISSUE #1089: Artifacts seem to contain wrong settings files
Content path cannot be found with the artifacts settings. (There is additional "../" in the path or so).

### PR DESCRIPTION
**Pull request by fayeinmay**
Using path traversal we can dynamically get the content path. You can still manually define the content path though.

Resolve #1089

### CODE REVIEW

File: GameServerLib/Config.cs [hunk 1]
```diff
@@ -90,6 +97,30 @@ private void LoadConfig(Game game, string json)
             MapData = ContentManager.GetMapData(GameConfig.Map);
             MapSpawns = ContentManager.GetMapSpawns(GameConfig.Map);
         }
+
+        private string getContentPath()
+        {
+            string result = null;
+            var path = new DirectoryInfo(Directory.GetCurrentDirectory());
+
+            while (result == null) {
```
Comment (danil179) [inline GameServerLib/Config.cs]: This can be an infinite loop (there are users that somehow delete their Content folder), use some counter to prevent this (depth >8 or so shouldn't be allowed).

File: GameServerLib/Config.cs [hunk 2]
```diff
@@ -90,6 +97,30 @@ private void LoadConfig(Game game, string json)
             MapData = ContentManager.GetMapData(GameConfig.Map);
             MapSpawns = ContentManager.GetMapSpawns(GameConfig.Map);
         }
+
+        private string getContentPath()
+        {
+            string result = null;
+            var path = new DirectoryInfo(Directory.GetCurrentDirectory());
```
Comment (danil179) [inline GameServerLib/Config.cs]: Use `Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);` instead of `Directory.GetCurrentDirectory()` (this may return something different from the exe folder, seems more reliable - see https://stackoverflow.com/questions/15653921/get-current-folder-path)

File: GameServerLib/Config.cs [hunk 3]
```diff
@@ -90,6 +97,30 @@ private void LoadConfig(Game game, string json)
             MapData = ContentManager.GetMapData(GameConfig.Map);
             MapSpawns = ContentManager.GetMapSpawns(GameConfig.Map);
         }
+
+        private string getContentPath()
```
Comment (danil179) [inline GameServerLib/Config.cs]: Start the first letter of a function with a capital letter in order to comply with our code style guidelines. (See https://github.com/LeagueSandbox/GameServer/blob/indev/CONTRIBUTING.md)

File: GameServerLib/Config.cs [hunk 4]
```diff
@@ -90,6 +97,30 @@ private void LoadConfig(Game game, string json)
...
+        {
+            string result = null;
+            var path = new DirectoryInfo(Directory.GetCurrentDirectory());
+
+            while (result == null) {
+                if (path == null) {
```
Comment (danil179) [inline GameServerLib/Config.cs]: We mostly use https://en.wikipedia.org/wiki/Indentation_style#Allman_style for brackets in the code. In this function you have two different code styles for bracket indentation. I think that it would be better to just stick with https://en.wikipedia.org/wiki/Indentation_style#Allman_style

**Review by danil179 — COMMENTED** [review]
For the most part, I think it is fine. I do see some infinite loop problems and 'working directory' problems (also, I have some comments about the code style). See my comments.

File: GameServerLib/Config.cs (hunk 1 above)
Comment (fayeinmay) [reply GameServerLib/Config.cs]: As we're using getParent() and C:\ does not have a Parent anymore, this should be fine. (path = null  -> break)

File: GameServerLib/Config.cs (hunk 4 above)
Comment (fayeinmay) [reply GameServerLib/Config.cs]: I Will do that, would be cool if someone could commit code-style format settings.

Comment (danil179) [reply GameServerLib/Config.cs]: This is actually issue #908. I think only the admin can add bots to the repo. There is also Github actions, but it never worked for me.

File: GameServerLib/Config.cs (hunk 1 above)
Comment (danil179) [reply GameServerLib/Config.cs]: Sounds fine. I mark it as resolved.

File: GameServerLib/Config.cs (hunk 4 above)
Comment (fayeinmay) [reply GameServerLib/Config.cs]: Oh, what I meant was just the settings file for rider or vs, but that would've sounded good too.

File: GameServerLib/Config.cs (hunk 2 above)
Comment (fayeinmay) [reply GameServerLib/Config.cs]: Done. Kept the old one if the new one is null.

**Review by danil179 — APPROVED** [review]
Approved. Didn't test as the code corrects only the problematic cases. I'll merge without testing.
