### PR TITLE
Resolve #903 -- Fix server crash while other client is open

### LINKED ISSUE #903: Reconnecting while another client is open crashes the server
https://github.com/LeagueSandbox/GameServer/blob/297cf6b5be9ba7e7a298754b81248691399d91d6/PacketDefinitions420/PacketHandlerManager.cs#L232

throw exception due to the new client handshake that will steal the peer address

https://github.com/LeagueSandbox/GameServer/blob/297cf6b5be9ba7e7a298754b81248691399d91d6/PacketDefinitions420/PacketHandlerManager.cs#L289

Blocking client to handshake while another client connects with the same player id will solve this problem. So simply add `else` or `if (_peers.ContainsKey(request.PlayerID))` in the handshake to `return;` and block the new client.

### PR DESCRIPTION
**Pull request by abosma**
_peers now first checks if the request.PlayerId already exists in HandleHandshake and returns to prevent the server from crashing.

### CODE REVIEW

File: PacketDefinitions420/PacketHandlerManager.cs [hunk 1]
```diff
@@ -264,39 +267,36 @@ public bool HandlePacket(Peer peer, ENet.Packet packet, Channel channelId)
...
         private bool HandleHandshake(Peer peer, byte[] data)
         {
             var request = PacketReader.ReadKeyCheckRequest(data);
             // TODO: keys for every player
             ulong playerID = (ulong)_blowfish.Decrypt(request.CheckId);
 
-            if (request.PlayerID != playerID)
+            if (request.PlayerID != playerID || _peers.ContainsKey(request.PlayerID))
             {
-                // wrong blowfish key
```
Comment (danil179) [inline PacketDefinitions420/PacketHandlerManager.cs:275]: You shouldn't remove these descriptive comments. Replace the comment with ` // Wrong blowfish key or player already connected`.

File: PacketDefinitions420/PacketHandlerManager.cs [hunk 2]
```diff
@@ -264,39 +267,36 @@ public bool HandlePacket(Peer peer, ENet.Packet packet, Channel channelId)
...
+            _playerManager.GetPeerInfo(request.PlayerID).IsStartedClient = true;
+            _playersConnected++;
+
+            Debug.WriteLine("Connected player No " + request.PlayerID);      
 
-            }
             _peers[request.PlayerID] = peer;
 
             bool result = true;
-            // inform players about their player numbers
```
Comment (danil179) [inline PacketDefinitions420/PacketHandlerManager.cs:292]: Don't remove important comments

File: PacketDefinitions420/PacketHandlerManager.cs [hunk 3]
```diff
@@ -264,39 +267,36 @@ public bool HandlePacket(Peer peer, ENet.Packet packet, Channel channelId)
...
+
             foreach (var player in _peers.Keys.ToArray())
             {
                 var response = new KeyCheckResponse(player, _playerClient[player]);
                 // TODO: fix casting
                 result = result && SendPacket((int)request.PlayerID, response.GetBytes(), Channel.CHL_HANDSHAKE);
             }
-            // only if all packets were sent successfully return true
```
Comment (danil179) [inline PacketDefinitions420/PacketHandlerManager.cs:299]: Again

**Review by danil179 — CHANGES_REQUESTED** [review]
Don't remove comments.

**Review by danil179 — APPROVED** [review]
Approved.
