### PR TITLE
Resolve #1227 Consumables Crash Hotfix

### LINKED ISSUE #1227: Consumables Crash
When using a consumable (stacked) item, such as a Health Potion, the item is removed before the script is removed, leading to a crash when attempting to remove the script.

### PR DESCRIPTION
**Pull request by cabeca1143**
*`RemoveItem` in `Inventory.cs` no longer tries to remove the same item's script twice, resulting on a crash

### CODE REVIEW

File: GameServerLib/Items/Inventory.cs [hunk 1]
```diff
@@ -117,8 +117,9 @@ public void RemoveItem(byte slot, IObjAiBase owner, int stacksToRemove = 1)
         {
             if (stacksToRemove < 0)
             {
-                throw new Exception("Stacks to be Removed can't be a negative number!");
+                stacksToRemove = 0;
```
Comment (lzardy) [inline GameServerLib/Items/Inventory.cs]: Revert this change.

File: GameServerLib/Items/Inventory.cs [hunk 2]
```diff
@@ -117,8 +117,9 @@ public void RemoveItem(byte slot, IObjAiBase owner, int stacksToRemove = 1)
...
             }
+
             var itemID = Items[slot].ItemData.ItemId;
             int finalStacks = Items[slot].StackCount - stacksToRemove;
```
Comment (lzardy) [inline GameServerLib/Items/Inventory.cs:125]: Remove lines 130 -> 136 (from the original file). This includes the `ItemScripts.Remove()` line.

File: GameServerLib/Items/Inventory.cs [hunk 3]
```diff
@@ -133,24 +134,14 @@ public void RemoveItem(byte slot, IObjAiBase owner, int stacksToRemove = 1)
...
+                    ItemScripts.Remove(itemID);
                 }
                 Items[slot] = null;
             }
             else
             {
                 Items[slot].SetStacks(finalStacks);
             }
-
-            if (!HasItemWithID(itemID) && owner != null)
```
Comment (lzardy) [inline GameServerLib/Items/Inventory.cs:145]: Revert deletion and change condition to
`if (finalStacks <= 0 || !HasItemWithID(itemID)) && owner != null && ItemScripts.ContainsKey(itemID)`.

**Review by lzardy — CHANGES_REQUESTED** [review]
Needs changes to maintain the edge case, that is, the case where an item which is not owned still has a script.

File: GameServerLib/Items/Inventory.cs (hunk 2 above)
Comment (cabeca1143) [reply GameServerLib/Items/Inventory.cs:125]: Done

File: GameServerLib/Items/Inventory.cs (hunk 3 above)
Comment (cabeca1143) [reply GameServerLib/Items/Inventory.cs:145]: Done

**Comment by lzardy** [comment]
Resolves #1227.

**Review by lzardy — APPROVED** [review]
Merging.

**Review by lzardy — CHANGES_REQUESTED** [review]
Fix AppVeyor issue (GameServerConsoleTests).

**Comment by cabeca1143** [comment]
Done

**Review by lzardy — APPROVED** [review]
Merged.
