### PR TITLE
Resolve #284 -- Fix red team spawning in blue fountain

### LINKED ISSUE #284: Players in purple team spawn in blue fountain
Title says everything.

### PR DESCRIPTION
**Pull request by FurkanS1821**
Refactored the whole code, red team will no longer spawn at blue fountain and both teams will spawn at the true position.

Refs #284

### CODE REVIEW

File: GameServerLib/Logic/GameObjects/Champion.cs [hunk 1]
```diff
@@ -21,12 +22,14 @@ public class Champion : Unit
         public int Skin { get; set; }
         private long _championHitFlagTimer;
         private uint _playerId;
+        private uint _playerTeamSpecialId;
```
Comment (MythicManiac) [inline GameServerLib/Logic/GameObjects/Champion.cs]: Could this be documented a bit? Maybe add a docstring here and on the constructor of `Champion`? It's pretty hard to tell what this does just by the name at least.

File: GameServerLib/Logic/GameObjects/Champion.cs [hunk 2]
```diff
@@ -138,10 +141,8 @@ public int getTeamSize()
                     case "blue":
                         blueTeamSize++;
                         break;
-                    case "purple":
-                        purpTeamSize++;
-                        break;
                     default:
```
Comment (MythicManiac) [inline GameServerLib/Logic/GameObjects/Champion.cs]: I don't think we should assign the purple team on a default callback. This doesn't enforce proper format in the configuration file, and we're likely going to add the possibility for more teams at a later date too.

File: GameServerLib/Logic/GameObjects/Champion.cs [hunk 3]
```diff
@@ -177,22 +177,38 @@ public int getTeamSize()
                 var p = config.Players[playerIndex];
                 playerTeam = p.Team;
             }
-            var x = 0;
-            var y = 0;
+
+            var toReturn = new Vector2();
```
Comment (MythicManiac) [inline GameServerLib/Logic/GameObjects/Champion.cs]: How about
```CS
var spawnsByTeam = new Dictionary<string, (whatever type the spawns are)> = new Dictionary<string, x>
{
    {"blue": config.MapSpawns.Blue},
    {"purple": config.MapSpawns.Purple}
}
// Check for key existance here
var spawns = spawnsByTeam[playerTeam.ToLower()];
return new Vector2(
    spawns[teamSize - 1].GetXForPlayer((int)_playerTeamSpecialId),
    spawns[teamSize - 1].GetYForPlayer((int)_playerTeamSpecialId)
);
// Even better than above ^ would be to add a `.GetForPlayer` method to the spawns that returns a Vector2,
// instead of having two different function for fetching floats.
```

File: GameServerLib/Logic/Players/PlayerManager.cs [hunk 4]
```diff
@@ -28,7 +30,7 @@ public void AddPlayer(KeyValuePair<string, PlayerConfig> p)
             };
             var player = new ClientInfo(
                 p.Value.Rank,
-                ((p.Value.Team.ToLower() == "blue") ? TeamId.TEAM_BLUE : TeamId.TEAM_PURPLE),
+                p.Value.Team.ToLower() == "blue" ? TeamId.TEAM_BLUE : TeamId.TEAM_PURPLE,
```
Comment (MythicManiac) [inline GameServerLib/Logic/Players/PlayerManager.cs]: I think this should be extracted to a function, rather than parsing here using an arbitrary magic string value for identification.

File: GameServerLib/Logic/Players/PlayerManager.cs [hunk 5]
```diff
@@ -13,6 +13,8 @@ public class PlayerManager
 
         private List<Pair<uint, ClientInfo>> _players = new List<Pair<uint, ClientInfo>>();
         private int _currentId = 1;
+        private uint _blueUserId = 0;
```
Comment (MythicManiac) [inline GameServerLib/Logic/Players/PlayerManager.cs]: Don't do this. Set up a `Dictionary<TeamId, int>` and use that as the counter for all teams

File: GameServerLib/Logic/Players/PlayerManager.cs [hunk 6]
```diff
@@ -28,7 +30,7 @@ public void AddPlayer(KeyValuePair<string, PlayerConfig> p)
             };
```
Comment (MythicManiac) [inline GameServerLib/Logic/Players/PlayerManager.cs]: Yeah, somewhere here just parse `var TeamId = GetTeamIdFromSomewhere();` and use that later on in the code. We want all teams to use the same code, and no separate if/else clauses for them like there currently is.

File: GameServerLib/Logic/GameObjects/Champion.cs (hunk 3 above)
Comment (MythicManiac) [inline GameServerLib/Logic/GameObjects/Champion.cs]: Adding to this, rather than using strings, use the `TeamId` enum we have.

File: GameServerLib/Logic/GameObjects/Champion.cs (hunk 2 above)
Comment (FurkanS1821) [inline GameServerLib/Logic/GameObjects/Champion.cs]: I made it default because it can be `red` instead of `purple`, and somewhere in the project assigning team is like:
```cs
if (team.ToLower() == "blue)
{ }
else
{ }
```
That's why I made it `default`.

File: GameServerLib/Logic/Players/PlayerManager.cs [hunk 7]
```diff
@@ -30,7 +43,7 @@ public void AddPlayer(KeyValuePair<string, PlayerConfig> p)
...
             var player = new ClientInfo(
                 p.Value.Rank,
-                p.Value.Team.ToLower() == "blue" ? TeamId.TEAM_BLUE : TeamId.TEAM_PURPLE,
+                GetTeamIdFromConfig(p),
```
Comment (MythicManiac) [inline GameServerLib/Logic/Players/PlayerManager.cs]:
```CS
var teamId = GetTeamIdFromConfig(p);
// use this on the player's constructor
// remove the if clause below and just do a singular
c = new Champion(p.Value.Champion, (uint)player.UserId, _userIdsPerTeam[teamId]++, p.Value.Runes);
c.SetTeam(teamId);
```
