### PR TITLE
Resolve #1426 -- Fix getting xp from the wrong team

### LINKED ISSUE #1426: Experience Given for Ally Deaths

### PR DESCRIPTION
**Pull request by T1ti**
Fix getting xp from allied minions/champions instead of enemies

### CODE REVIEW

File: GameServerLib/GameObjects/AttackableUnits/AttackableUnit.cs [hunk 1]
```diff
@@ -700,7 +700,13 @@ public virtual void Die(IDeathData data)
...
                 if (!(obj is IMonster))
                 {
-                    var champs = _game.ObjectManager.GetChampionsInRangeFromTeam(Position, _game.Map.MapScript.MapScriptMetadata.AIVars.EXPRadius, Team, true);
+                    var enemyTeam = TeamId.TEAM_BLUE;
+                    if (Team == TeamId.TEAM_BLUE)
+                    {
+                        enemyTeam = TeamId.TEAM_PURPLE;
+                    }
+
+                    var champs = _game.ObjectManager.GetChampionsInRangeFromTeam(Position, _game.Map.MapScript.MapScriptMetadata.AIVars.EXPRadius, enemyTeam, true);
```
Comment (lzardy) [inline GameServerLib/GameObjects/AttackableUnits/AttackableUnit.cs]: Utilize `CustomConvert.GetEnemyTeam()`.

**Review by lzardy — APPROVED** [review]
Good.
