### PR TITLE
Resolve #1020 -- Fix Recall

### LINKED ISSUE #1020: Recall animation abruptly disappears
When pressing B to issue recall, the animation is abruptly disappears after a very short time, though the recall seems to continue normally.

### PR DESCRIPTION
**Pull request by lzardy**
This is a sort-of temporary fix for recall abruptly stopping.
Resolve #1020 
- Co-authored by [danil179](https://github.com/danil179)

### CODE REVIEW

**Comment by danil179** [comment]
I did a very similar solution in #1077. I'm actually not sure when the unit order type get updated, is it always the move order one?

File: Content/LeagueSandbox-Scripts/Buffs/Global/Recall.cs [hunk 1]
```diff
@@ -55,16 +58,20 @@ public void OnUpdateMoveOrder(IObjAiBase unit)
...
             {
-                buff.DeactivateBuff();
+                if (unit.MoveOrder != OrderType.Hold && unit.MoveOrder != OrderType.Stop)
+                {
+                    buff.DeactivateBuff();
+                }
+                else
+                {
+                    // After the callback ends, it will remove the listener, so we make a new one before the callback ends.
+                    ApiEventManager.OnUnitUpdateMoveOrder.AddListener(this, unit, OnUpdateMoveOrder, true);
```
Comment (danil179) [inline Content/LeagueSandbox-Scripts/Buffs/Global/Recall.cs:68]: You can avoid it by simply changing the true to false for 'singleinstance' callback.

File: Content/LeagueSandbox-Scripts/Buffs/Global/Recall.cs [hunk 2]
```diff
@@ -55,16 +58,20 @@ public void OnUpdateMoveOrder(IObjAiBase unit)
             var buff = unit.GetBuffWithName("Recall");
             if (buff != null)
             {
-                buff.DeactivateBuff();
+                if (unit.MoveOrder != OrderType.Hold && unit.MoveOrder != OrderType.Stop)
```
Comment (danil179) [inline Content/LeagueSandbox-Scripts/Buffs/Global/Recall.cs]: Is it that `unit.MoveOrder` will never miss the current move order? (say for example that I update the move order very fast with many spells/taunt and so on).

**Review by danil179 — COMMENTED** [review]
Seems fine.

File: Content/LeagueSandbox-Scripts/Buffs/Global/Recall.cs (hunk 2 above)
Comment (danil179) [reply Content/LeagueSandbox-Scripts/Buffs/Global/Recall.cs]: There are race conditions in the case of multiple listeners, where one of them changes the MoveOrder too. This will cause all the listeners that are called after to miss this update event and rely on a new OrderType. We need to choose what kind of behavior we expect.

Comment (lzardy) [reply Content/LeagueSandbox-Scripts/Buffs/Global/Recall.cs]: I don't see what you mean. All listeners are called per-update.

Comment (danil179) [reply Content/LeagueSandbox-Scripts/Buffs/Global/Recall.cs]: @microsoftv Let's assume that there are 2 listeners: A,B. A changes the move order in some way (for example, calls StopMovement). That will change unit.MoveOrder. Now the code for B starts and it uses different unit.MoveOrder.

Comment (lzardy) [reply Content/LeagueSandbox-Scripts/Buffs/Global/Recall.cs]: Alright, then ideally the event should have the order when triggered. I would prefer if we PR'd this one alongside your PR, as the recall in this PR removes the listener.

Comment (danil179) [reply Content/LeagueSandbox-Scripts/Buffs/Global/Recall.cs]: My PR will never get merged (or at least not in the near term future) as there are no active reviewers besides me. I suggest that you will just take my code (for the addition of order type parameter to the event) from there and copy it in your PR. If you want you can add "coauthored by" line to the PR and I'll add it to the commit.

Comment (lzardy) [reply Content/LeagueSandbox-Scripts/Buffs/Global/Recall.cs]: Done.

**Review by danil179 — APPROVED** [review]
Approved. There is still this problem of "You can avoid it by simply changing the true to false for 'singleinstance' callback.", but as it is not so important I'll open an issue about that.
