### PR TITLE
[Scripting] Item Actives

### LINKED ISSUE #1085: Empty Spell Slots
All spell slots should be filled with BaseSpell in ObjAiBase initialization to prevent out of bounds slot crashes.

### LINKED ISSUE #1087: Magic Damage Reduction
Magic damage is reduced with MagicPenetration rather than MagicResist (ahem, since IntWars).

### PR DESCRIPTION
**Pull request by lzardy**
* Scripting:
  * Added SpellCastItem (location and targeted) for items which require manual casted missile spells.
  * Re-implemented DeathfireGrasp as an example.
  * Added location targeted SpellCast.
* Enums:
  * Expanded SpellSlotType and added start index for each.
* ObjAiBase & Champion:
  * Used SpellSlotType in place of spell slot magic numbers.
  
Resolve #1087, #1085, #1084

### CODE REVIEW

File: GameServerLib/API/ApiFunctionManager.cs [hunk 1]
```diff
@@ -659,6 +664,20 @@ public static void SpellCast(IObjAiBase caster, int slot, SpellSlotType slotType
...
+            // Apply the spell to the TempItemSlot.
+            caster.SetSpell(itemSpellName, (byte)SpellSlotType.TempItemSlot, true);
+            SpellCast(caster, 0, SpellSlotType.TempItemSlot, fireWithoutCasting, target, overrideCastPos, isForceCastingOrChanneling, overrideForceLevel, updateAutoAttackTimer, useAutoAttackSpell);
+        }
+
+        public static void SpellCastItem(IObjAiBase caster, string itemSpellName, Vector2 pos, Vector2 endPos, bool fireWithoutCasting, Vector2 overrideCastPos, bool isForceCastingOrChanneling = false, int overrideForceLevel = -1, bool updateAutoAttackTimer = false, bool useAutoAttackSpell = false)
+        {
+            // Apply the spell to the TempItemSlot.
+            caster.SetSpell(itemSpellName, (byte)SpellSlotType.TempItemSlot, true);
+            SpellCast(caster, 0, SpellSlotType.TempItemSlot, pos, endPos, fireWithoutCasting, overrideCastPos, null, isForceCastingOrChanneling, overrideForceLevel, updateAutoAttackTimer, useAutoAttackSpell);
```
Comment (danil179) [inline GameServerLib/API/ApiFunctionManager.cs:678]: What is the 'null' here for?

**Review by danil179 — APPROVED** [review]
Seems fine. I'll test it later (in the next few days).

File: GameServerLib/API/ApiFunctionManager.cs (hunk 1 above)
Comment (lzardy) [reply GameServerLib/API/ApiFunctionManager.cs:678]: castTarget variable.

Comment (danil179) [reply GameServerLib/API/ApiFunctionManager.cs:678]: But it doesn't appear in the lines before. (See the function above this one)
It is like all the parameters are shifted in ones of the calls to SpellCast.

Comment (danil179) [reply GameServerLib/API/ApiFunctionManager.cs:678]: Seems like there are two very similar SpellCast functions signatures. I think we should pass all the parameters in sort of container and not like that as the code tends to be very confusing in this current way (10+ parameters).

Comment (lzardy) [reply GameServerLib/API/ApiFunctionManager.cs:678]: The above function uses the other SpellCast which is target only, so it doesn't have position variables.
This function uses the original SpellCast function which has both position and target variables.
