### PR TITLE
Resolve #1075, Resolve #723 -- Scripts Hot Reload

### LINKED ISSUE #723: Add scripts file watcher
To reload scripts on any changes automatically.

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@Gan` in `#random🍝`.

### LINKED ISSUE #1075: !reloadscripts does not work as expected
!reloadscripts does not reload scripts with the new scripting API.

Logger logs: DEBUG LeagueSandbox.GameServer.Content.Package - Loaded all C# scripts from package: LeagueSandbox-Scripts from [here](https://github.com/LeagueSandbox/GameServer/blob/7efead4ca12e9220b7a54544fc22bdc648865c05/GameServerLib/Content/Package.cs#L174)
but the scripts are not reloaded until relaunching the GameServer.

For example, modifying [LeagueSandbox-Scripts/Champions/Ezreal/Q.cs](https://github.com/LeagueSandbox/GameServer/blob/indev/Content/LeagueSandbox-Scripts/Champions/Ezreal/Q.cs) , saving the file, and then using !reloadscripts does not reload the changes into the game.

The only way to "hot reload" changes is to swap to another champion and back, which is buggy, requires leveling again, and sometimes breaks spell casting.

### PR DESCRIPTION
**Pull request by david-ix1**
Resolve #1075 Fixed the !reloadscripts command.
Resolve #723 implemented Script Hot Reloading.
The new command is !hotreload 1/0, which helps write scripts quickly.

Added reference of GameMaths to the script engine in order to use MathExtensions in scripts.

Also consolidated the method documentations for Spell.cs and Buff.cs that were strewn across the classes and their interfaces.

### CODE REVIEW

File: GameServerLib/Game.cs [hunk 1]
```diff
@@ -232,19 +238,68 @@ public void InitializePacketHandlers()
             RequestHandler.Register<ViewRequest>(new HandleView(this).HandlePacket);
         }
 
+        /// <summary>
+        /// Enables or disables the hot reloading of scripts. Used only for development.
+        /// </summary>
+        public void EnableHotReload(bool status)
+        {
+            string scriptsPath = Config.ContentManager.GetLoadedPackage("LeagueSandbox-Scripts").PackagePath;
```
Comment (danil179) [inline GameServerLib/Game.cs]: There should be a way of doing so without hardcoding the package name ("LeagueSandbox-Scripts"). Maybe it is somewhere in the Config file.

File: GameServerLib/Game.cs [hunk 2]
```diff
@@ -232,19 +238,68 @@ public void InitializePacketHandlers()
...
+            {
+                ScriptsHotReloadWatcher = new FileSystemWatcher
+                {
+                    Path = scriptsPath,
+                    IncludeSubdirectories = true,
+                    EnableRaisingEvents = true,
+                    NotifyFilter = NotifyFilters.LastWrite,
+                    Filter = "*.*",
+                };
+                ScriptsHotReloadWatcher.Changed += ScriptsChanged;
```
Comment (danil179) [inline GameServerLib/Game.cs:266]: Generally I expect some race conditions when using events that replace existing spells. Hopefully it will not crash anything.

File: GameServerLib/GameObjects/Buff.cs [hunk 3]
```diff
@@ -5,76 +5,46 @@
...
+using LeagueSandbox.GameServer.API;
 
 namespace LeagueSandbox.GameServer.GameObjects
 {
     public class Buff : Stackable, IBuff
     {
         // Crucial Vars.
-        protected Game _game;
+        protected Game Game;
+        protected CSharpScriptEngine ScriptEngine;
```
Comment (danil179) [inline GameServerLib/GameObjects/Buff.cs]: Naming of protected variables is mostly treated like private variables in the code. I suggest to revert their names to start with underscore.

File: GameServerLib/GameObjects/Buff.cs [hunk 4]
```diff
@@ -5,76 +5,46 @@
...
-        public string Name { get; private set; }
-        /// <summary>
-        /// Spell which caused this buff to be applied.
-        /// </summary>
-        public ISpell OriginSpell { get; private set; }
-        /// <summary>
-        /// Slot of this buff instance. Maximum allowed is 255 due to packets.
-        /// </summary>
+        protected bool InfiniteDuration;
+        protected bool Remove;
```
Comment (danil179) [inline GameServerLib/GameObjects/Buff.cs]: Naming of protected variables is mostly treated like private variables in the code. I suggest to change them to private variables (if possible) and revert their names to start with underscore.

File: GameServerLib/GameObjects/Spell/Spell.cs [hunk 5]
```diff
@@ -16,32 +16,30 @@ namespace LeagueSandbox.GameServer.GameObjects.Spell
...
-        private CSharpScriptEngine _scriptEngine;
-        private Game _game;
-        protected NetworkIdManager _networkIdManager;
+        private readonly Game _game;
+        private readonly CSharpScriptEngine _scriptEngine;
         private uint _futureProjNetId;
         private ISpellScript _spellScript;
 
-        public ICastInfo CastInfo { get; private set; } = new CastInfo();
+        protected NetworkIdManager NetworkIdManager;
```
Comment (danil179) [inline GameServerLib/GameObjects/Spell/Spell.cs]: Change this variable to be private if possible. If not, revert the name to start with underscore.

**Review by danil179 — CHANGES_REQUESTED** [review]
Th main point is:
1. Most of the protected variables are named with underscore, so just revert some of the naming changes (we need to decide how to name protected vars one day).

File: GameServerLib/Game.cs (hunk 1 above)
Comment (lzardy) [reply GameServerLib/Game.cs]: You should change the method to support multiple scripts packages.
I would recommend using `GetAllLoadedPackages`.
You will need to add a variable to the Package class which stores "whether or not this package contains loaded scripts".
After that, you will need to add each of the `Package.PackageName` packages that have scripts loaded to the watcher.
To save on resources, make sure you have the filter set to `"*.cs*"`.

Comment (davidivkovic) [reply GameServerLib/Game.cs]: I agree, the problem here was that a FileSystemWatcher takes a single string as the Path argument, that means the watcher is watching one root directory and its subdirectories.

The solution to support multiple packages would be to:
    a) Watch the parent directory of all packages
    b) Use multiple watchers, one for each package

File: GameServerLib/Game.cs (hunk 2 above)
Comment (davidivkovic) [reply GameServerLib/Game.cs:266]: So far everything is working as expected

File: GameServerLib/Game.cs [hunk 6]
```diff
@@ -232,19 +238,62 @@ public void InitializePacketHandlers()
...
+
+            if (status && ScriptsHotReloadWatcher == null)
+            {
+                ScriptsHotReloadWatcher = new FileSystemWatcher
+                {
+                    Path = scriptsPath,
+                    IncludeSubdirectories = true,
+                    EnableRaisingEvents = true,
+                    NotifyFilter = NotifyFilters.LastWrite,
+                    Filter = "*.*",
```
Comment (lzardy) [inline GameServerLib/Game.cs:264]: The filter should be `"*.cs*"`.

Comment (davidivkovic) [reply GameServerLib/Game.cs:264]: Does not work for some odd reason.

Comment (lzardy) [reply GameServerLib/Game.cs:264]: Try `"*.cs"` instead.

Comment (davidivkovic) [reply GameServerLib/Game.cs:264]: It's very strange, but it only seems to work with `"*.*"`

Comment (lzardy) [reply GameServerLib/Game.cs:264]: It works fine with `"*.cs"`, changing the file via Visual Studio while debugging will not trigger the file changed event. However, changing the file via a text editor will.

Comment (davidivkovic) [reply GameServerLib/Game.cs:264]: Do you think we should keep it so that the files can be edited with Visual Studio? The watcher will only run during development when explicitly enabling hot reload anyways

Comment (lzardy) [reply GameServerLib/Game.cs:264]: It isn't entirely necessary I agree, however I believe it should at least be kept as an issue for the future. You should be able to merge as-is, and I'll just make an issue.

Comment (davidivkovic) [reply GameServerLib/Game.cs:264]: I agree.

**Review by danil179 — APPROVED** [review]
Approved.
