### PR TITLE
Resolve #1129 -- Fix Collision Re-pathing

### LINKED ISSUE #1129: Collision Repathing Issue Regression
Somewhere along the way, OnCollision repathing has regressed, where units no longer re-path on collision, and instead simply stay at the position they were teleported to when colliding.

### PR DESCRIPTION
**Pull request by lzardy**
Resolve #1129
* Champion:
  * Removed useless teleport logic from OnCollision and ObjBuilding is no longer collideable.
* ObjAiBase:
  * Removed useless OnCollision, as AttackableUnit now accounts for movement/waypoints, so too should it account for collision repathing.
* AttackableUnit:
  * OnCollision properly teleports out of terrain and objects, and optionally repaths afterwards.
  * SetPosition properly stops movement when repathing should not be done.
  * TeleportTo repath option added.

### CODE REVIEW

File: GameServerLib/GameObjects/AttackableUnits/AI/Champion.cs [hunk 1]
```diff
@@ -356,26 +356,13 @@ public override void Die(IAttackableUnit killer)
         public override void OnCollision(IGameObject collider, bool isTerrain = false)
         {
             // TODO: Pathfinding should be responsible for pathing around units so collisions with other units never occur (or at least very little).
-            // Collisions only occur between buildings.
-            if (MovementParameters != null || !(collider is IObjBuilding || collider is IBaseTurret || isTerrain == true))
+            // As a result, collisions for Champions should only occur between buildings and terrain.
+            if (!(collider is IBaseTurret || isTerrain == true))
             {
                 return;
```
Comment (danil179) [inline GameServerLib/GameObjects/AttackableUnits/AI/Champion.cs]: I don't really understand this part (I probably forgot something here). If we have a chain of inheritance Champion<->ObjAiBase <-> AttackableUnit <-> ..., I expect each to handle its priorities and then to continue propagating the collision to the next ones. Why isn't that the case with the Champion class colliding with let's say a minion? Do we have upcasting to AttackableUnit when checking this collision?

File: GameServerLib/GameObjects/AttackableUnits/AttackableUnit.cs [hunk 2]
```diff
@@ -239,27 +246,38 @@ public override void OnCollision(IGameObject collider, bool isTerrain = false)
...
 
+            Vector2 exit = Vector2.Zero;
+
             if (isTerrain)
             {
+                // TODO: Replace this with event listener publishing.
                 var onCollideWithTerrain = _game.ScriptEngine.GetStaticMethod<Action<IGameObject>>(Model, "Passive", "onCollideWithTerrain");
                 onCollideWithTerrain?.Invoke(this);
+
+                if (isTerrain)
```
Comment (danil179) [inline GameServerLib/GameObjects/AttackableUnits/AttackableUnit.cs]: Why do we have a recheck on this variable?

**Review by danil179 — COMMENTED** [review]
I'll have to test this. Will reply in 24h. Currently it seems that most of the logic migrated to AttackableUnit, which I think is a good change. I'm not sure if we really want to tell the client that the collision teleports are real teleports, but I guess it just works well.

**Review by danil179 — APPROVED** [review]
Approved. Didn't test.
