### PR TITLE
Packets Update Part 3 + Champion Respawn Spell Lock fix

### LINKED ISSUE #1258: Spells Locked On-Respawn
Champions that have a PAR type different from `MANA`, `ENERGY` or `WIND` have an issue where they can't cast any spell (not even summoners spells or recall) after they die.

The issue fixes itself when the character levels up.

### PR DESCRIPTION
**Pull request by cabeca1143**
*Updated `DebugMessage`, `EmoticonPacketResponse`, `InhibitorStateUpdate`, `PauseGame`, `QueryStatus`, `UnpauseGame`, `InhibitorStateUpdate`, and `ViewResponse` packets.

*Removed `SpawnMonster`, `SpawnAzirTurret` and `InhibitorDeathAnimation` and used the proper packets in their place.

 *Introduced `GetClientInfoWithPlayerId` to `PlayerManager`

*Fixed #1258

### CODE REVIEW

File: GameServerCore/Packets/Interfaces/IPacketNotifier.cs [hunk 1]
```diff
@@ -495,19 +463,14 @@ public interface IPacketNotifier
         /// </summary>
         /// <param name="seconds">Amount of time till the pause ends.</param>
         /// <param name="showWindow">Whether or not to show a pause window.</param>
-        void NotifyPauseGame(int seconds, bool showWindow);
+        void NotifyPausePacket(Tuple<uint, ClientInfo> player, int seconds, bool isTournament);
```
Comment (lzardy) [inline GameServerCore/Packets/Interfaces/IPacketNotifier.cs]: Rather than passing in the tuple, simply pass in the ClientInfo. Do this for all packet functions which were changed to use a Tuple.

File: GameServerCore/Packets/Interfaces/IPacketNotifier.cs [hunk 2]
```diff
@@ -554,7 +517,7 @@ public interface IPacketNotifier
         /// </summary>
         /// <param name="unpauser">Unit that unpaused the game.</param>
         /// <param name="showWindow">Whether or not to show a window before unpausing (delay).</param>
-        void NotifyResumeGame(IAttackableUnit unpauser, bool showWindow);
+        void NotifyResumePacket(IChampion unpauser, Tuple<uint, ClientInfo> player, bool isDelayed);
```
Comment (lzardy) [inline GameServerCore/Packets/Interfaces/IPacketNotifier.cs]: Change Tuple to ClientInfo.

File: GameServerCore/Packets/Interfaces/IPacketNotifier.cs [hunk 3]
```diff
@@ -963,5 +947,12 @@ void NotifyWaypointListWithSpeed
             float backDistance = 0,
             float travelTime = 0
         );
+        /// <summary>
+        /// Sends a packet to the specified player detailing that their request to view something with their camera has been acknowledged.
+        /// </summary>
+        /// <param name="userId">User to send the packet to.</param>
+        /// <param name="request">ViewRequest housing information about the camera's view.</param>
+        /// TODO: Verify if this is the correct implementation.
+        void NotifyWorld_SendCamera_Server_Acknologment(int userId, ViewRequest request);
```
Comment (lzardy) [inline GameServerCore/Packets/Interfaces/IPacketNotifier.cs:957]:
```suggestion
        /// TODO: Fix LeaguePackets Typos.
        void NotifyWorld_SendCamera_Server_Acknologment(int userId, ViewRequest request);
```

File: GameServerCore/IPlayerManager.cs [hunk 4]
```diff
@@ -13,5 +13,6 @@ public interface IPlayerManager
         ClientInfo GetClientInfoByChampion(IChampion champ);
         ClientInfo GetPeerInfo(long playerId);
         List<Tuple<uint, ClientInfo>> GetPlayers(bool includeBots = false);
+        Tuple<uint, ClientInfo> GetClientInfoWithPlayerId(int playerId);
```
Comment (lzardy) [inline GameServerCore/IPlayerManager.cs]: Remove this function and simply pass in the ClientInfo to the packet notifier functions which used this.
```suggestion
```

File: GameServerLib/Game.cs [hunk 5]
```diff
@@ -410,7 +410,10 @@ public void Pause()
                 return;
             }
             IsPaused = true;
-            PacketNotifier.NotifyPauseGame((int)PauseTimeLeft, true);
+            foreach(var player in PlayerManager.GetPlayers())
+            {
+                PacketNotifier.NotifyPausePacket(player, (int)PauseTimeLeft, true);
```
Comment (lzardy) [inline GameServerLib/Game.cs]:
```suggestion
                PacketNotifier.NotifyPausePacket(player.Item2, (int)PauseTimeLeft, true);
```

File: GameServerLib/Packets/PacketHandlers/HandleStartGame.cs [hunk 6]
```diff
@@ -82,7 +82,7 @@ public override bool HandlePacket(int userId, StartGameRequest req)
                             _game.PacketNotifier.NotifyNPC_LevelUp(player.Item2.Champion);
                             if (_game.IsPaused)
                             {
-                                 _game.PacketNotifier.NotifyPauseGame((int)_game.PauseTimeLeft, true);
+                                 _game.PacketNotifier.NotifyPausePacket(_playerManager.GetClientInfoWithPlayerId((int)peerInfo.PlayerId), (int)_game.PauseTimeLeft, true);
```
Comment (lzardy) [inline GameServerLib/Packets/PacketHandlers/HandleStartGame.cs]:
```suggestion
                                 _game.PacketNotifier.NotifyPausePacket(peerInfo, (int)_game.PauseTimeLeft, true);
```

File: GameServerLib/Packets/PacketHandlers/HandleUnpauseReq.cs [hunk 7]
```diff
@@ -27,8 +27,10 @@ public override bool HandlePacket(int userId, UnpauseRequest req)
             IChampion unpauser = null;
 
             unpauser = _playerManager.GetPeerInfo(userId).Champion;
-
-            _game.PacketNotifier.NotifyResumeGame(unpauser, true);
+            foreach(var player in _playerManager.GetPlayers())
+            {
+                _game.PacketNotifier.NotifyResumePacket(unpauser, player ,true);
```
Comment (lzardy) [inline GameServerLib/Packets/PacketHandlers/HandleUnpauseReq.cs]:
```suggestion
                _game.PacketNotifier.NotifyResumePacket(unpauser, player.Item2, true);
```

File: GameServerLib/Packets/PacketHandlers/HandleUnpauseReq.cs [hunk 8]
```diff
@@ -37,7 +39,10 @@ public override bool HandlePacket(int userId, UnpauseRequest req)
             };
             timer.Elapsed += (sender, args) =>
             {
-                _game.PacketNotifier.NotifyResumeGame(unpauser, false);
+                foreach(var player in _playerManager.GetPlayers())
+                {
+                    _game.PacketNotifier.NotifyResumePacket(unpauser, player, false);
```
Comment (lzardy) [inline GameServerLib/Packets/PacketHandlers/HandleUnpauseReq.cs]:
```suggestion
                    _game.PacketNotifier.NotifyResumePacket(unpauser, player.Item2, false);
```

File: GameServerLib/Players/PlayerManager.cs [hunk 9]
```diff
@@ -101,5 +101,17 @@ public ClientInfo GetClientInfoByChampion(IChampion champ)
 
             return _players;
         }
+
+        public Tuple<uint, ClientInfo> GetClientInfoWithPlayerId(int playerId)
```
Comment (lzardy) [inline GameServerLib/Players/PlayerManager.cs]: Remove this function.

File: PacketDefinitions420/PacketNotifier.cs [hunk 10]
```diff
@@ -2060,10 +1984,18 @@ public void NotifyNPC_SetAutocast(int userId, IObjAiBase caster, ISpell spell, b
         /// </summary>
         /// <param name="seconds">Amount of time till the pause ends.</param>
         /// <param name="showWindow">Whether or not to show a pause window.</param>
-        public void NotifyPauseGame(int seconds, bool showWindow)
+        public void NotifyPausePacket(Tuple<uint, ClientInfo> player, int seconds, bool isTournament)
```
Comment (lzardy) [inline PacketDefinitions420/PacketNotifier.cs]:
```suggestion
        public void NotifyPausePacket(ClientInfo player, int seconds, bool isTournament)
```

File: PacketDefinitions420/PacketNotifier.cs [hunk 11]
```diff
@@ -2060,10 +1984,18 @@ public void NotifyNPC_SetAutocast(int userId, IObjAiBase caster, ISpell spell, b
...
         {
-            var pg = new PauseGame(seconds, showWindow);
-            _packetHandlerManager.BroadcastPacket(pg, Channel.CHL_S2C);
+            var pg = new PausePacket
+            {
+                //Check if sender ID should be the person that requested the pause or just 0
+                SenderNetID = 0,
+                ClientID = (int)player.Item2.ClientId,
```
Comment (lzardy) [inline PacketDefinitions420/PacketNotifier.cs]:
```suggestion
                ClientID = (int)player.ClientId,
```

File: PacketDefinitions420/PacketNotifier.cs [hunk 12]
```diff
@@ -2060,10 +1984,18 @@ public void NotifyNPC_SetAutocast(int userId, IObjAiBase caster, ISpell spell, b
...
+                IsTournament = isTournament,
+                PauseTimeRemaining = seconds
+            };
+            //I Assumed that, since the packet requires idividual client IDs, that it also sends the packets individually, by useing the SendPacket Channel, double check if that's valid.
+            _packetHandlerManager.SendPacket((int)player.Item2.Champion.GetPlayerId(), pg.GetBytes(), Channel.CHL_S2C);
```
Comment (lzardy) [inline PacketDefinitions420/PacketNotifier.cs]:
```suggestion
            _packetHandlerManager.SendPacket((int)player.PlayerId, pg.GetBytes(), Channel.CHL_S2C);
```

File: PacketDefinitions420/PacketNotifier.cs [hunk 13]
```diff
@@ -2208,19 +2130,23 @@ public void NotifyRequestReskin(int userId, Tuple<uint, ClientInfo> player)
         /// </summary>
         /// <param name="unpauser">Unit that unpaused the game.</param>
         /// <param name="showWindow">Whether or not to show a window before unpausing (delay).</param>
-        public void NotifyResumeGame(IAttackableUnit unpauser, bool showWindow)
+        public void NotifyResumePacket(IChampion unpauser, Tuple<uint, ClientInfo> player, bool isDelayed)
```
Comment (lzardy) [inline PacketDefinitions420/PacketNotifier.cs]:
```suggestion
        public void NotifyResumePacket(IChampion unpauser, ClientInfo player, bool isDelayed)
```

File: PacketDefinitions420/PacketNotifier.cs [hunk 14]
```diff
@@ -2208,19 +2130,23 @@ public void NotifyRequestReskin(int userId, Tuple<uint, ClientInfo> player)
...
         {
-            UnpauseGame upg;
+            var resume = new ResumePacket
+            {
+                Delayed = isDelayed,
+                ClientID = (int)player.Item2.ClientId
```
Comment (lzardy) [inline PacketDefinitions420/PacketNotifier.cs]:
```suggestion
                ClientID = (int)player.ClientId
```

File: PacketDefinitions420/PacketNotifier.cs [hunk 15]
```diff
@@ -2208,19 +2130,23 @@ public void NotifyRequestReskin(int userId, Tuple<uint, ClientInfo> player)
...
+                resume.SenderNetID = 0;
             }
             else
             {
-                upg = new UnpauseGame(unpauser.NetId, showWindow);
+                resume.SenderNetID = unpauser.NetId;
             }
 
-            _packetHandlerManager.BroadcastPacket(upg, Channel.CHL_S2C);
+            _packetHandlerManager.SendPacket((int)player.Item2.PlayerId, resume.GetBytes(), Channel.CHL_S2C);
```
Comment (lzardy) [inline PacketDefinitions420/PacketNotifier.cs]:
```suggestion
            _packetHandlerManager.SendPacket((int)player.PlayerId, resume.GetBytes(), Channel.CHL_S2C);
```

**Review by lzardy — CHANGES_REQUESTED** [review]
A few changes needed.

File: GameServerCore/IPlayerManager.cs [hunk 16]
```diff
@@ -13,5 +13,6 @@ public interface IPlayerManager
         ClientInfo GetClientInfoByChampion(IChampion champ);
         ClientInfo GetPeerInfo(long playerId);
         List<Tuple<uint, ClientInfo>> GetPlayers(bool includeBots = false);
+        ClientInfo GetClientInfoWithPlayerId(int playerId);
```
Comment (lzardy) [inline GameServerCore/IPlayerManager.cs]: Remove this function and use `GetPeerInfo`.
```suggestion
```

File: GameServerLib/Players/PlayerManager.cs [hunk 17]
```diff
@@ -101,5 +101,17 @@ public ClientInfo GetClientInfoByChampion(IChampion champ)
 
             return _players;
         }
+
+        public ClientInfo GetClientInfoWithPlayerId(int playerId)
```
Comment (lzardy) [inline GameServerLib/Players/PlayerManager.cs]: Remove this function and use `GetPeerInfo`.

**Review by lzardy — CHANGES_REQUESTED** [review]
Small changes still required.

File: GameServerLib/Players/PlayerManager.cs (hunk 17 above)
Comment (cabeca1143) [reply GameServerLib/Players/PlayerManager.cs]: Oh i didnt notice there was a Function that did this already

**Review by lzardy — APPROVED** [review]
Good to go.
