### PR TITLE
Resolve #1183 -- Passive Scripts Fix

### LINKED ISSUE #1183: Scripts for Passives aren't being read

### PR DESCRIPTION
**Pull request by cabeca1143**
* Removed class PassiveData from CharData.cs Since the only used parameter was "PassiveAbilityName" and the function within was essentially useless.
* Introduced ICharScript.cs and CharScript.cs for scripting passives and to be used in the future with champion specific adjustments.
* Introduced LoadPassiveScript in ObjAiBase to properly load passives, also added the OnUpdate and OnDeactivate functions in there for them.
* Updated Champion's Passive Scripts to reflect the new template for them.

Resolve #1183

Props for Lizardy for his guidance.

### CODE REVIEW

File: GameServerLib/Content/CharData.cs [hunk 1]
```diff
@@ -25,33 +25,6 @@ public class GlobalData : IGlobalData
         public float PercentEXPBonusMaximum { get; set; } = 5.000f;
     }
 
-    public class PassiveData : IPassiveData
```
Comment (lzardy) [inline GameServerLib/Content/CharData.cs]: Keep PassiveData, you can leave the `GetPassiveAbilityNameFromScriptFile` function removed for now, but keep the `TODO` comment.

File: GameServerLib/GameObjects/AttackableUnits/AI/ObjAIBase.cs [hunk 2]
```diff
@@ -77,6 +79,10 @@ public class ObjAiBase : AttackableUnit, IObjAiBase
         /// </summary>
         public IAttackableUnit TargetUnit { get; set; }
         public Dictionary<short, ISpell> Spells { get; }
+        public ISpell Passive { get; }
```
Comment (lzardy) [inline GameServerLib/GameObjects/AttackableUnits/AI/ObjAIBase.cs]: Remove this and use the `Spells` variable as it contains the passive spell already.

File: GameServerLib/Content/CharData.cs [hunk 3]
```diff
@@ -92,6 +65,7 @@ public CharData(ContentManager contentManager)
         public PrimaryAbilityResourceType ParType { get; private set; } = PrimaryAbilityResourceType.MANA;
 
         public string[] SpellNames { get; private set; } = new string[4];
+        public string PassiveAbilityName { get; set; } = "";
```
Comment (lzardy) [inline GameServerLib/Content/CharData.cs]: Remove this in favor of keeping PassiveData.

File: GameServerLib/Content/CharData.cs [hunk 4]
```diff
@@ -169,6 +142,8 @@ public void Load(string name)
                 SpellsUpLevels[i] = file.GetIntArray("Data", $"SpellsUpLevels{i + 1}", SpellsUpLevels[i]);
             }
 
+            PassiveAbilityName = file.GetString("Data", "Passive1LuaName", "");
```
Comment (lzardy) [inline GameServerLib/Content/CharData.cs]: Use the PassiveLuaName variable instead of PassiveAbilityName.

File: GameServerLib/GameObjects/AttackableUnits/AI/ObjAIBase.cs (hunk 2 above)
Comment (cabeca1143) [reply GameServerLib/GameObjects/AttackableUnits/AI/ObjAIBase.cs]: I used the Spells, just remnants of my testing

File: GameServerCore/Domain/ICharData.cs [hunk 5]
```diff
@@ -37,7 +37,7 @@ public interface ICharData
         float[] AttackProbabilities { get; }
         string[] ExtraSpells { get; }
         // TODO: Verify if we want this to be an array.
-        IPassiveData Passive { get; }
+        public IPassiveData PassiveData { get; }
```
Comment (lzardy) [inline GameServerCore/Domain/ICharData.cs]: Remove the `public`

File: GameServerLib/GameObjects/AttackableUnits/AI/ObjAIBase.cs [hunk 6]
```diff
@@ -138,6 +145,9 @@ public class ObjAiBase : AttackableUnit, IObjAiBase
                         Spells[i] = new Spell.Spell(game, this, CharData.SpellNames[i], (byte)i);
                     }
                 }
+                //Passive
+                Spells[(int)SpellSlotType.PassiveSpellSlot] = new Spell.Spell(game, this, CharData.PassiveData.PassiveLuaName, (int)SpellSlotType.PassiveSpellSlot);
```
Comment (danil179) [inline GameServerLib/GameObjects/AttackableUnits/AI/ObjAIBase.cs]: `CharData.PassiveData.PassiveLuaName` is used here, but right after we have ` if (!string.IsNullOrEmpty(CharData.PassiveData.PassiveLuaName))`. Is it defined or not?

**Review by danil179 — CHANGES_REQUESTED** [review]
I have one comment regarding the verification of the passive spell name.

File: GameServerLib/GameObjects/AttackableUnits/AI/ObjAIBase.cs (hunk 6 above)
Comment (lzardy) [reply GameServerLib/GameObjects/AttackableUnits/AI/ObjAIBase.cs]: The purpose is so that any spell not defined in the content data gets assigned BaseSpell.

**Review by danil179 — APPROVED** [review]
Approved. Didn't test as it is a new system that is hard to test. Further modification can be resolved with issues.
