### PR TITLE
Resolve #1156 -- Fix Mislabeled PrimaryAbilityResourceTypes

### LINKED ISSUE #1156: Fix enum fields for PrimaryAbilityResourceType
https://github.com/LeagueSandbox/GameServer/blob/e9c816578cdda19cd0bae345cb82a364ad70fd3c/GameServerCore/Enums/PrimaryAbilityResourceType.cs

### PR DESCRIPTION
**Pull request by cabeca1143**
*Fixed Mislabeled PrimaryAbilityResourceTypes.

Now Champions Get assigned their proper PARType instead of being defaulted to MANA.

Resolve #1156

### CODE REVIEW

File: GameServerCore/Enums/PrimaryAbilityResourceType.cs [hunk 1]
```diff
@@ -3,16 +3,16 @@
     public enum PrimaryAbilityResourceType : byte
     {
         MANA = 0,
```
Comment (lzardy) [inline GameServerCore/Enums/PrimaryAbilityResourceType.cs:5]: All caps still.

Comment (cabeca1143) [reply GameServerCore/Enums/PrimaryAbilityResourceType.cs:5]: Yeah, it is actually all caps.

**Review by danil179 — APPROVED** [review]
Approved. Names are claimed to be more accurate. Origin of the names is unknown.
