### PR TITLE
Particles, Projectiles, and Extras: QOL Changes

### LINKED ISSUE #831: Projectile problem
When we add multi-projectile __(that are same troy and id)__
for example
```
AddProjectile("SivirQ",owner.X,owner.Y,trueCoords.X,trueCoords.Y);
AddProjectile("SivirQReturn",trueCoords.X,trueCoords.Y,owner.X,owner.Y);
```
the server will crash for "the object already added in", then jump up "GameObject.cs" then tag "AddObject".

### PR DESCRIPTION
**Pull request by lzardy**
1. Fixed not being able to have multiple projectiles per spell
2. Projectiles' OriginSpell and SpellData references are now public (read only)
3. Spells now contain references to all of their projectiles
4. Added particle visibility checks
5. Replaces projectile and particle packets with LeaguePackets' versions (implementations are likely incomplete, check comments for details)
6. Adds extra packets (just so it doesn't have to be done later)
7. Removes many of the unused PacketDefinitions420 packets (there are more, but decided to only remove ones that were replaced in this PR)
Close #831 and #308

### CODE REVIEW

File: GameServerCore/Domain/GameObjects/IProjectile.cs [hunk 1]
```diff
@@ -7,5 +7,8 @@ public interface IProjectile : IObjMissile
         List<IGameObject> ObjectsHit { get; }
         IAttackableUnit Owner { get; }
         int ProjectileId { get; }
+        ISpellData SpellData { get; }
+        ISpell OriginSpell { get; }
```
Comment (danil179) [inline GameServerCore/Domain/GameObjects/IProjectile.cs:11]: So `ISpellData` isn't in `ISpell`? And why do we really want to expose it in the interface?

File: GameServerLib/GameObjects/Spells/Spell.cs [hunk 2]
```diff
@@ -95,7 +96,8 @@ public virtual bool Cast(float x, float y, float x2, float y2, IAttackableUnit u
             X2 = x2;
             Y2 = y2;
             Target = u;
-            FutureProjNetId = _networkIdManager.GetNewNetId();
+            uint FutureProjNetId = _networkIdManager.GetNewNetId();
```
Comment (danil179) [inline GameServerLib/GameObjects/Spells/Spell.cs]: Not used?

File: GameServerLib/GameObjects/Spells/Spell.cs [hunk 3]
```diff
@@ -30,7 +31,7 @@ public class Spell : ISpell
         public float CurrentCooldown { get; protected set; }
         public float CurrentCastTime { get; protected set; }
         public float CurrentChannelDuration { get; protected set; }
-        public uint FutureProjNetId { get; protected set; }
+        public List<IProjectile> Projectiles { get; protected set; }
```
Comment (danil179) [inline GameServerLib/GameObjects/Spells/Spell.cs]: Consider different implementation like hash table.

File: GameServerLib/GameObjects/Spells/Spell.cs [hunk 4]
```diff
@@ -231,17 +238,23 @@ public void AddProjectile(string nameMissile, float fromX, float fromY, float to
                 SpellData.MissileSpeed,
                 nameMissile,
                 SpellData.Flags,
-                FutureProjNetId
+                projNetId,
+                isServerOnly
             );
+            if (p != null)
```
Comment (danil179) [inline GameServerLib/GameObjects/Spells/Spell.cs]: Why `p` will be `null`?

File: GameServerLib/ObjectManager.cs [hunk 5]
```diff
@@ -59,6 +59,42 @@ public void Update(float diff)
...
+                //TODO: Implement visibility checks for projectiles here (should be similar to particles below), make
+                //Make sure to account for server only, globally visible (everyone sees it) projectiles, and normal projectiles:
+                //1. Nidalee Q is affected by visibility checks, but is server only 
+                //2. Ezreal R is globally visible, and is server only
+                //3. Every other projectile that is not server only, and is affected by visibility checks (normal projectiles)
+
+                var particle = obj as IParticle;
+                foreach (var team in Teams)
+                {
+                    if (particle != null)
```
Comment (danil179) [inline GameServerLib/ObjectManager.cs]: Should be placed before the `foreach`

**Review by danil179 — COMMENTED** [review]
I did fast review. I'll approve later.

File: GameServerLib/GameObjects/Spells/Spell.cs (hunk 4 above)
Comment (danil179) [reply GameServerLib/GameObjects/Spells/Spell.cs]: And this is a good point to use `?.`

File: GameServerLib/GameObjects/Spells/Spell.cs (hunk 2 above)
Comment (lzardy) [reply GameServerLib/GameObjects/Spells/Spell.cs]: It is used only in Spell.cs for NotifyCastSpell.

File: GameServerCore/Domain/GameObjects/IProjectile.cs (hunk 1 above)
Comment (lzardy) [reply GameServerCore/Domain/GameObjects/IProjectile.cs:11]: We can probably remove it from Projectile altogether since it has OriginSpell.

Comment (lzardy) [reply GameServerCore/Domain/GameObjects/IProjectile.cs:11]: Nevermind, it is the projectile spell's spelldata, not the spell that casts it.

Comment (lzardy) [reply GameServerCore/Domain/GameObjects/IProjectile.cs:11]: If it is part of the interface, scripts can use it for values, such as scaling, damage, particles, flags, etc. It would probably help to eliminate a lot of constants in scripts.

File: GameServerLib/GameObjects/Spells/Spell.cs (hunk 4 above)
Comment (lzardy) [reply GameServerLib/GameObjects/Spells/Spell.cs]: Only did it out of instinct, didn't have any cases yet where it was null.

File: GameServerCore/Domain/GameObjects/IProjectile.cs (hunk 1 above)
Comment (danil179) [reply GameServerCore/Domain/GameObjects/IProjectile.cs:11]: Seems ok.

File: GameServerLib/GameObjects/Spells/Spell.cs (hunk 2 above)
Comment (danil179) [reply GameServerLib/GameObjects/Spells/Spell.cs]: This is local variable

Comment (lzardy) [reply GameServerLib/GameObjects/Spells/Spell.cs]: Yes, what about it?

File: GameServerLib/GameObjects/Spells/Spell.cs (hunk 3 above)
Comment (lzardy) [reply GameServerLib/GameObjects/Spells/Spell.cs]: So, a dictionary?

File: GameServerLib/GameObjects/Spells/Spell.cs (hunk 2 above)
Comment (danil179) [reply GameServerLib/GameObjects/Spells/Spell.cs]: Where do you use it?

File: GameServerLib/GameObjects/Spells/Spell.cs (hunk 3 above)
Comment (lzardy) [reply GameServerLib/GameObjects/Spells/Spell.cs]: Should I make the key an int for their position in the dictionary or uint for the projectile's netID?

File: GameServerLib/GameObjects/Spells/Spell.cs (hunk 2 above)
Comment (danil179) [reply GameServerLib/GameObjects/Spells/Spell.cs]: Ok, I missed the usage.

Comment (danil179) [reply GameServerLib/GameObjects/Spells/Spell.cs]: Do you really not need it? (to insert it into the projectiles list)

Comment (lzardy) [reply GameServerLib/GameObjects/Spells/Spell.cs]: If you want, I could delete the variable and put `_networkIdManager.GetNewNetId()` into `NotifyCastSpell`.

Comment (danil179) [reply GameServerLib/GameObjects/Spells/Spell.cs]: From what I remember, you need to add this id to the first projectile (like Nidalee spear). Check if Nidalee spear work with this PR.

File: GameServerLib/GameObjects/Spells/Spell.cs (hunk 3 above)
Comment (danil179) [reply GameServerLib/GameObjects/Spells/Spell.cs]: Yeah, by NetId.

File: GameServerLib/GameObjects/Spells/Spell.cs (hunk 4 above)
Comment (lzardy) [reply GameServerLib/GameObjects/Spells/Spell.cs]: Removed the check.

File: GameServerLib/ObjectManager.cs (hunk 5 above)
Comment (lzardy) [reply GameServerLib/ObjectManager.cs]: Done.

File: GameServerLib/GameObjects/Spells/Spell.cs (hunk 2 above)
Comment (lzardy) [reply GameServerLib/GameObjects/Spells/Spell.cs]: Made it private and re-assigned netId after each projectile is added.

File: GameServerLib/GameObjects/Spells/Spell.cs [hunk 6]
```diff
@@ -43,6 +44,8 @@ public class Spell : ISpell
         private Game _game;
         protected NetworkIdManager _networkIdManager;
 
+        private uint FutureProjNetId;
```
Comment (danil179) [inline GameServerLib/GameObjects/Spells/Spell.cs]: Disagree with style guide.

**Review by danil179 — CHANGES_REQUESTED** [review]
Code style problems.

**Review by danil179 — APPROVED** [review]
Approved.
