### PR TITLE
Resolve #1070 -- Fix Commands

### LINKED ISSUE #1070: Chat doesn't work
Currently, the chat in game doesn't work because the communication channel is for LoadingScreen packets.

### PR DESCRIPTION
**Pull request by lzardy**
Some loading screen packets do not use the loading screen channel, so this fix accounts for loading screen packets which use the communication channel.

Resolve #1070

### CODE REVIEW

**Comment by danil179** [comment]
I'm closing and reopening the PR as there are problems with appveyor.

**Comment by danil179** [comment]
If you can please rebase your PR by changing the commit message.

File: PacketDefinitions420/PacketHandlerManager.cs [hunk 1]
```diff
@@ -62,7 +62,7 @@ internal void InitializePacketConvertors()
                 {
                     if (attr is PacketType)
                     {
-                        if (((PacketType)attr).ChannelId == Channel.CHL_LOADING_SCREEN)
+                        if (((PacketType)attr).ChannelId == Channel.CHL_LOADING_SCREEN || ((PacketType)attr).ChannelId == Channel.CHL_COMMUNICATION)
```
Comment (danil179) [inline PacketDefinitions420/PacketHandlerManager.cs:65]: When this `Channel.CHL_COMMUNICATION` channel used? If it is used in both LoadScreen and Game as I suspect (I think it is used for ingame chat) then this solution will disable chat?

**Review by danil179 — COMMENTED** [review]
Some comments.

File: PacketDefinitions420/PacketHandlerManager.cs (hunk 1 above)
Comment (lzardy) [reply PacketDefinitions420/PacketHandlerManager.cs:65]: Chat is currently disabled because convertor does not support the communication channel. This PR fixes that.

Comment (danil179) [reply PacketDefinitions420/PacketHandlerManager.cs:65]: Just to make sure:
There are no Game packets in this communication channel and all the packets there are LoadingScreen ones?

Comment (lzardy) [reply PacketDefinitions420/PacketHandlerManager.cs:65]: Yes, the communication channel is only for LoadScreen packets. Bit confusing I know, but it contains the chat packets.

**Review by danil179 — APPROVED** [review]
Approved.
