### PR TITLE
Fix Chat

### LINKED ISSUE #1072: ! Chat commands not publishing ChatMessageRequest
Typing !ad 100, or any other !command in the chat box, does not trigger the `new HandleChatBoxMessage(this).HandlePacket` in [Game.cs](https://github.com/LeagueSandbox/GameServer/blob/286a358681ba2c3a9bf683591933f2e2393bb65a/GameServerLib/Game.cs#L207)

### PR DESCRIPTION
**Pull request by lzardy**
* Replaced Chat packet reader with LeaguePackets' version.
* HandlePacket in PacketHandlerManager now accounts for the separation between Game and LoadScreen packets.
* HandlePacket in PacketHandlerManager no longer relies on a PacketHeader class, instead doing the byte reading itself.

Resolve #1072

### CODE REVIEW

File: PacketDefinitions420/PacketHandlerManager.cs [hunk 1]
```diff
@@ -258,17 +259,34 @@ public bool BroadcastPacket(byte[] data, Channel channelNo, PacketFlags flag = P
...
-                case GamePacketID.Waypoint_Acc:
-                case GamePacketID.OnReplication_Acc:
-                    break;
+                var loadScreenPacketId = (LoadScreenPacketID)reader.ReadByte();
+
+                convertor = GetConvertor(loadScreenPacketId);
+            }
+            else
+            {
+                var gamePacketId = (GamePacketID)reader.ReadByte();
```
Comment (danil179) [inline PacketDefinitions420/PacketHandlerManager.cs:273]: That will not fully work, but this is part of #779. Should be fixed later.

File: PacketDefinitions420/PacketHandlerManager.cs [hunk 2]
```diff
@@ -258,17 +259,34 @@ public bool BroadcastPacket(byte[] data, Channel channelNo, PacketFlags flag = P
...
+                // TODO: Verify if this is needed.
+                var netID = reader.ReadInt32();
```
Comment (danil179) [inline PacketDefinitions420/PacketHandlerManager.cs]: This `netId` variable is not needed in the current code.

File: PacketDefinitions420/PacketDefinitions/C2S/ChatMessage.cs [hunk 3]
```diff
@@ -2,12 +2,13 @@
 using System.IO;
 using System.Text;
 using GameServerCore.Packets.Enums;
+using LeaguePackets;
 
 namespace PacketDefinitions420.PacketDefinitions.C2S
 {
     public class ChatMessage
```
Comment (danil179) [inline PacketDefinitions420/PacketDefinitions/C2S/ChatMessage.cs]: I think you can now delete this class if we use the LeaguePackets version.

**Review by danil179 — CHANGES_REQUESTED** [review]
I think you can delete ChatMessage if we use LeaguePackets. Also, the use of netId can be removed as this variable seems to me unused.

File: PacketDefinitions420/PacketHandlerManager.cs [hunk 4]
```diff
@@ -258,17 +259,32 @@ public bool BroadcastPacket(byte[] data, Channel channelNo, PacketFlags flag = P
 
         public bool HandlePacket(Peer peer, byte[] data, Channel channelId)
         {
-            var header = new PacketHeader(data);
-            var convertor = GetConvertor(header.Cmd, channelId);
+            var reader = new BinaryReader(new MemoryStream(data));
+            RequestConvertor convertor;
 
-            switch (header.Cmd)
+            if (channelId == Channel.CHL_COMMUNICATION || channelId == Channel.CHL_LOADING_SCREEN)
```
Comment (danil179) [inline PacketDefinitions420/PacketHandlerManager.cs:265]: I think you should also add the `ChannelID.QuickChat` channel to here. Not sure if it is used here, but should be generally.

**Review by danil179 — COMMENTED** [review]
Adding a channel is needed.

File: PacketDefinitions420/PacketHandlerManager.cs (hunk 4 above)
Comment (danil179) [reply PacketDefinitions420/PacketHandlerManager.cs:265]: I'm opening it as an issue. Ignore this.

File: PacketDefinitions420/PacketHandlerManager.cs [hunk 5]
```diff
@@ -258,17 +259,32 @@ public bool BroadcastPacket(byte[] data, Channel channelNo, PacketFlags flag = P
...
+                var gamePacketId = (GamePacketID)reader.ReadByte();
+
+                convertor = GetConvertor(gamePacketId, channelId);
+
+                switch (gamePacketId)
+                {
+                    case GamePacketID.World_SendCamera_Server:
+                    case GamePacketID.Waypoint_Acc:
+                    case GamePacketID.OnReplication_Acc:
+                        break;
```
Comment (danil179) [inline PacketDefinitions420/PacketHandlerManager.cs:282]: Actually, I don't think this code is doing anything. Will open issue about that.

**Review by danil179 — APPROVED** [review]
