### PR TITLE
Fix the subrecipe bug and re-enable usage of the Shop class

### LINKED ISSUE #664: Make ItemBuyRequests acknowledge subrecipe components
Make ItemBuyRequests acknowledge subrecipe components, so that building a Blade of the Ruined King will consume long swords and vampiric scepters in the buyer's inventory instead of ignoring them.

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@Veykril` in `#general`.

### PR DESCRIPTION
**Pull request by Veykril**
Closes #664.

### CODE REVIEW

**Review by FurkanS1821 — APPROVED** [review]
If this is tested to be working, I can't see anything wrong.

File: GameServerLib/Items/InventoryManager.cs [hunk 1]
```diff
@@ -1,8 +1,10 @@
 ﻿using System.Collections;
 using System.Collections.Generic;
 using System.Linq;
+using CommandLine;
```
Comment (MatthewFrench) [inline GameServerLib/Items/InventoryManager.cs]: Is this necessary?

**Review by MatthewFrench — COMMENTED** [review]
Just one import comment, besides that looks good!
