### PR TITLE
Resolve #282 -- Fix Loading Config Causing Crash

### LINKED ISSUE #282: Loading Config before Program.Run causes Ninject to crash
Config needs to be changed to load after Program.Run.

### PR DESCRIPTION
**Pull request by MatthewFrench**
Removed Config from server parameters that was causing a Ninject crash.

Refs #282

### CODE REVIEW

File: GameServerLib/Program.cs [hunk 1]
```diff
@@ -11,9 +11,9 @@ namespace LeagueSandbox.GameServer
     /// </summary>
     public class GameServerLauncher
     {
-        public static void LaunchServer(ushort serverPort, Config config)
+        public static void LaunchServer(ushort serverPort, String configJson)
```
Comment (MythicManiac) [inline GameServerLib/Program.cs]: how about just `string` instead of `String` ?
