### PR TITLE
Resolve #278 -- Only complete UpdateStats

### LINKED ISSUE #278: Movements of the enemy team not working properly.
When you gain vision on a minion or champion it won't move until it performs another action (e.g. attacking)

### PR DESCRIPTION
**Pull request by Maufeat**
"Partial" UpdateStats aren't working and thus breaks the whole GameObject/Unit Stats and sets for example the Movement to 0.

### CODE REVIEW

File: GameServerLib/Logic/GameObjects/GameObjects.cs [hunk 1]
```diff
@@ -252,9 +252,9 @@ public bool IsVisibleByTeam(TeamId team)
         public void SetVisibleByTeam(TeamId team, bool visible)
         {
             _visibleByTeam[team] = visible;
-            if (this is Unit)
+            if(this is Unit)
```
Comment (MythicManiac) [inline GameServerLib/Logic/GameObjects/GameObjects.cs]: Don't remove this whitespace :<

**Comment by MythicManiac** [comment]
Commit message looks good now, great :+1:
