### PR TITLE
Fix Vision

### LINKED ISSUE #580: Vision blocked by buildings
_game.Map.NavGrid.IsAnythingBetween(kv.Value, o) Applies to buildings which it should not. Turrets cannot attack you if you move behind an inhibitor, nexus, or another turret. Inhibitors and Nexus' that you should be able to attack/target are untargetable due to vision being blocked by the map's inhibitor/nexus.

### PR DESCRIPTION
**Pull request by lzardy**
Fixes the issue where units would teleport to different corners of the map after re-entering vision.
Replaced NotifyEnterVision with LeaguePackets' NotifyEnterVisibilityClient. 
Replaced NotifySetHealth with LeaguePackets' NotifyEnterLocalVisibilityClient.

Fixed sometimes losing vision of a unit when a raycast stops where it started.

Fixed not being able to see through the NavGridFlag 0x40 (SEE_THROUGH, or TransparentWall), this consequently fixes not being able to attack units that are behind a see through part of the NavGrid, such as Inhibitors and Nexus'.
**NOTE: This is only applicable if the NavGrid has the flag.**
In the case were it does not, unless you decide to edit the NavGrid, use the fix suggested by #845.

When merging, close #580 and #843.

### CODE REVIEW

**Comment by danil179** [comment]
"This is due to the function IsAnythingBetween in ObjectManager.cs being poorly coded"

It doesn't seems that you changed something in this function. So this fix bypass that problem?

**Comment by lzardy** [comment]
> "This is due to the function IsAnythingBetween in ObjectManager.cs being poorly coded"
> 
> It doesn't seems that you changed something in this function. So this fix bypass that problem?

Comment is no longer valid, issue was resolved.

**Comment by danil179** [comment]
Try to rebase in some way that will not show changed files with all the files that got rebased. I think that if you rebase your actual commits on all the previous PRs in order (first, all the previous PRs and then your actual commits), GitHub will notice that and show only the "real" commits.

File: PacketDefinitions420/PacketNotifier.cs [hunk 1]
```diff
@@ -721,23 +721,71 @@ public void NotifyLeaveVision(IGameObject o, TeamId team)
...
+                SkinName = u.Model,
+                OverrideSpells = false,
+                ModelOnly = false,
+                ReplaceCharacterPackage = false,
+                ID = 0
+            };
+            enterVis.LookAtPosition = new Vector3(1, 0, 0);
+            if (u is IObjAiBase)
+            {
+                _ = ((IObjAiBase)u).GetBuffs().ToList(); // buffList left for when someone decides to finish this
```
Comment (danil179) [inline PacketDefinitions420/PacketNotifier.cs]: This is major style issue. Don't use `_` for naming. Why do you need the casting? I think it's redundant.

File: GameServerLib/Packets/PacketHandlers/HandleSpawn.cs [hunk 2]
```diff
@@ -122,13 +122,13 @@ public override bool HandlePacket(int userId, SpawnRequest req)
             {
                 // Shop (blue team)
                  _game.PacketNotifier.NotifyStaticObjectSpawn(userId, 0xff10c6db);
```
Comment (danil179) [inline GameServerLib/Packets/PacketHandlers/HandleSpawn.cs]: Wrong indentation.

File: GameServerLib/Packets/PacketHandlers/HandleSpawn.cs [hunk 3]
```diff
@@ -94,14 +94,14 @@ public override bool HandlePacket(int userId, SpawnRequest req)
...
                     if (champion.IsVisibleByTeam(peerInfo.Champion.Team))
                     {
-                         _game.PacketNotifier.NotifyEnterVision(userId, champion);
+                        _game.PacketNotifier.NotifyEnterVisibilityClient(champion, champion.Team, userId);
                     }
                 }
                 else if (kv.Value is IInhibitor || kv.Value is INexus)
                 {
                     var inhibtor = (IAttackableUnit)kv.Value;
                      _game.PacketNotifier.NotifyStaticObjectSpawn(userId, inhibtor.NetId);
```
Comment (danil179) [inline GameServerLib/Packets/PacketHandlers/HandleSpawn.cs:103]: Wrong indentation.

File: GameServerLib/Content/NavGrid.cs [hunk 4]
```diff
@@ -490,34 +510,33 @@ public float CastRaySqr(Vector2 origin, Vector2 destination, bool inverseRay = f
...
+            var il = (int)greatestdist;
+            var dx = distx / greatestdist;
+            var dy = disty / greatestdist;
             int i;
-            for (i = 0; i <= il; i++)
+            for (i = 0; i < il; i++)
             {
-                if (IsWalkable(x1, y1) == inverseRay)
+                //TODO: Implement bush logic (preferably near here)
+                if (IsWalkable(x1, y1) == checkWalkable && IsSeeThrough(x1, y1) == checkWalkable)
```
Comment (danil179) [inline GameServerLib/Content/NavGrid.cs:529]: Add comment: `// Only works for navgrids with SeeThrough flags`

File: GameServerLib/Maps/SummonersRift.cs [hunk 5]
```diff
@@ -273,15 +273,14 @@ public void Init()
...
             var sightRange = 1700;
 
-            _game.ObjectManager.AddObject(new Inhibitor(_game, "OrderInhibitor", TeamId.TEAM_BLUE, collisionRadius, 835, 3400, sightRange, 0xffd23c3e)); //top
-            _game.ObjectManager.AddObject(new Inhibitor(_game, "OrderInhibitor", TeamId.TEAM_BLUE, collisionRadius, 2785, 3000, sightRange, 0xff4a20f1)); //mid
-            _game.ObjectManager.AddObject(new Inhibitor(_game, "OrderInhibitor", TeamId.TEAM_BLUE, collisionRadius, 3044, 1070, sightRange, 0xff9303e1)); //bot
-            _game.ObjectManager.AddObject(new Inhibitor(_game, "ChaosInhibitor", TeamId.TEAM_PURPLE, collisionRadius, 10960, 13450, sightRange, 0xff6793d0)); //top
-            _game.ObjectManager.AddObject(new Inhibitor(_game, "ChaosInhibitor", TeamId.TEAM_PURPLE, collisionRadius, 11240, 11490, sightRange, 0xffff8f1f)); //mid
-            _game.ObjectManager.AddObject(new Inhibitor(_game, "ChaosInhibitor", TeamId.TEAM_PURPLE, collisionRadius, 13200, 11200, sightRange, 0xff26ac0f)); //bot
-
+            _game.ObjectManager.AddObject(new Inhibitor(_game, "OrderInhibitor", TeamId.TEAM_BLUE, collisionRadius, 853.368f, 3345.1645f, sightRange, 0xffd23c3e)); //top exact
```
Comment (danil179) [inline GameServerLib/Maps/SummonersRift.cs:277]: Add comment: `// TODO: Generate exact positions from content files`

File: GameServerCore/Packets/Interfaces/IPacketNotifier.cs [hunk 6]
```diff
@@ -35,8 +35,9 @@ public interface IPacketNotifier
         void NotifyDebugPacket(int userId, byte[] data);
         void NotifyEditBuff(IBuff b, int stacks);
         void NotifyEmotions(Emotions type, uint netId);
-        void NotifyEnterVision(IGameObject o, TeamId team);
-        void NotifyEnterVision(int userId, IChampion champion);
+        void NotifyEnterLocalVisibilityClient(IAttackableUnit unit, int userId = 0);
```
Comment (danil179) [inline GameServerCore/Packets/Interfaces/IPacketNotifier.cs:38]: I don't really like that `userId` is the last argument. I get why you did that (you need default value), but still it looks weird.

File: GameServerLib/Packets/PacketHandlers/HandleSpawn.cs [hunk 7]
```diff
@@ -122,13 +122,13 @@ public override bool HandlePacket(int userId, SpawnRequest req)
             {
                 // Shop (blue team)
                  _game.PacketNotifier.NotifyStaticObjectSpawn(userId, 0xff10c6db);
-                 _game.PacketNotifier.NotifySetHealth(userId, 0xff10c6db);
+                _game.PacketNotifier.NotifyEnterLocalVisibilityClient(userId, 0xff10c6db);
```
Comment (danil179) [inline GameServerLib/Packets/PacketHandlers/HandleSpawn.cs:126]: `0xff10c6db` is some hardcoded `NetId`. Add comment: `// TODO: Generate shop NetId to avoid hard-coding`

File: PacketDefinitions420/PacketNotifier.cs [hunk 8]
```diff
@@ -721,23 +721,71 @@ public void NotifyLeaveVision(IGameObject o, TeamId team)
             }
         }
 
-        public void NotifyEnterVision(IGameObject o, TeamId team)
+        // TODO: Fix IsAnythingBetween randomly losing vision often, which ends up spamming this as well
+        public void NotifyEnterVisibilityClient(IAttackableUnit u, TeamId team, int userId = 0)
```
Comment (danil179) [inline PacketDefinitions420/PacketNotifier.cs:724]: Related implementation: #832

**Review by danil179 — CHANGES_REQUESTED** [review]
Style issues and some discussion.

File: GameServerCore/Packets/Interfaces/IPacketNotifier.cs (hunk 6 above)
Comment (lzardy) [reply GameServerCore/Packets/Interfaces/IPacketNotifier.cs:38]: Can I ignore this? I need the userId = 0 for the check if userId == 0, then broadcast. Perhaps we can discuss if EnterLocalVisibilityClient should Broadcast?

File: PacketDefinitions420/PacketNotifier.cs (hunk 8 above)
Comment (lzardy) [reply PacketDefinitions420/PacketNotifier.cs:724]: Not sure if you want me to change something, the implementation linked has many features that my PR lacks, such as SyncId and MovementData, thus my implementation can't change much.

File: GameServerCore/Packets/Interfaces/IPacketNotifier.cs (hunk 6 above)
Comment (danil179) [reply GameServerCore/Packets/Interfaces/IPacketNotifier.cs:38]: Add flag `IsBroadcast`.

File: PacketDefinitions420/PacketNotifier.cs (hunk 8 above)
Comment (danil179) [reply PacketDefinitions420/PacketNotifier.cs:724]: I just wanted to relate this in GitHub (so I'll have a link).

**Review by danil179 — APPROVED** [review]
Approved. Consider changing the `userId` to broadcast flag where needed. (if it's possible)
