### PR TITLE
Resolve #1016 -- Server Crashes when Casting Heal Twice Fast

### LINKED ISSUE #1016: Server Crashes when Casting Heal Twice Fast
Happens when running with 2 players with everything the same besides blowfishKey and PlayerID. Doesn't happen with 1 player.

The reason for this crash is that there is buff removal process that somehow tries to remove non-existing buff due to the buff itself remove itself on update (as there are 2 buffs when casting heal).

See:
https://github.com/LeagueSandbox/GameServer/blob/c411d54a87d30f76b0058fa655dae6e0ad864de0/GameServerLib/ObjectManager.cs#L142

### PR DESCRIPTION
**Pull request by Gistix**
Fixed summoner spell buff crash by copying the list of buffs before removal

Refs #1016

### CODE REVIEW

File: GameServerLib/ObjectManager.cs [hunk 1]
```diff
@@ -134,7 +134,7 @@ public void Update(float diff)
                 var ai = u as IObjAiBase;
                 if (ai != null)
                 {
-                    var tempBuffs = ai.GetBuffs();
+                    var tempBuffs = new List<GameServerCore.Domain.IBuff> (ai.GetBuffs ());
```
Comment (ATypescriptEnjoyer) [inline GameServerLib/ObjectManager.cs]: could you remove the spaces before the parenthesis, looks a bit weird

**Review by danil179 — APPROVED** [review]
Approved.
