### PR TITLE
Resolve #1096 -- Fix SpellMissile IsValidTarget

### LINKED ISSUE #1096: SpellFlags Incorrect for Neutral
SpellMissiles' IsValidTarget function checks for neutral unit type before checking if all unit types are affected.
This causes neutral units to not take damage.

### PR DESCRIPTION
**Pull request by lzardy**
Resolve #1096

* SpellMissile:
  * All IsValidTarget implementations changed to properly handle all spell flags.
  * IsValidTarget's team-based checks properly override unit-based checks (NEUTRAL is a special case, as the flag is a unit-based flag).

### CODE REVIEW

File: GameServerLib/GameObjects/Spell/Missile/SpellCircleMissile.cs [hunk 1]
```diff
@@ -187,60 +187,81 @@ protected override bool IsValidTarget(IAttackableUnit unit)
...
-            {
-                return false;
-            }
+            bool valid = true;
 
-            if (unit.Team == TeamId.TEAM_NEUTRAL && !SpellOrigin.SpellData.Flags.HasFlag(SpellDataFlags.AffectNeutral))
+            if (unit.Team == CastInfo.Owner.Team && !SpellOrigin.SpellData.Flags.HasFlag(SpellDataFlags.AffectFriends))
             {
-                return false;
+                valid = false;
```
Comment (danil179) [inline GameServerLib/GameObjects/Spell/Missile/SpellCircleMissile.cs]: I think you can return `false` here instead of continuing checking (not sure that C# can see this optimization very easily).

File: GameServerLib/GameObjects/Spell/Missile/SpellCircleMissile.cs [hunk 2]
```diff
@@ -187,60 +187,81 @@ protected override bool IsValidTarget(IAttackableUnit unit)
...
             }
 
             if (unit.Team != CastInfo.Owner.Team && unit.Team != TeamId.TEAM_NEUTRAL && !SpellOrigin.SpellData.Flags.HasFlag(SpellDataFlags.AffectEnemies))
             {
-                return false;
+                valid = false;
```
Comment (danil179) [inline GameServerLib/GameObjects/Spell/Missile/SpellCircleMissile.cs]: I think you can return `false` here instead of continuing checking (not sure that C# can see this optimization very easily).

File: GameServerLib/GameObjects/Spell/Missile/SpellCircleMissile.cs [hunk 3]
```diff
@@ -187,60 +187,81 @@ protected override bool IsValidTarget(IAttackableUnit unit)
...
             }
 
             if (unit.IsDead && !SpellOrigin.SpellData.Flags.HasFlag(SpellDataFlags.AffectDead))
             {
-                return false;
+                valid = false;
```
Comment (danil179) [inline GameServerLib/GameObjects/Spell/Missile/SpellCircleMissile.cs]: I think you can return `false` here instead of continuing checking (not sure that C# can see this optimization very easily).

File: GameServerLib/GameObjects/Spell/Missile/SpellCircleMissile.cs [hunk 4]
```diff
@@ -187,60 +187,81 @@ protected override bool IsValidTarget(IAttackableUnit unit)
                 return false;
```
Comment (danil179) [inline GameServerLib/GameObjects/Spell/Missile/SpellCircleMissile.cs:187]: Why this function not simply call the base class `SpellMissile`? What are the differences?

File: GameServerLib/GameObjects/Spell/Missile/SpellMissile.cs [hunk 5]
```diff
@@ -200,60 +200,81 @@ public override void SetToRemove()
...
-            {
-                return false;
-            }
+            bool valid = true;
 
-            if (unit.Team == TeamId.TEAM_NEUTRAL && !SpellOrigin.SpellData.Flags.HasFlag(SpellDataFlags.AffectNeutral))
+            if (unit.Team == CastInfo.Owner.Team && !SpellOrigin.SpellData.Flags.HasFlag(SpellDataFlags.AffectFriends))
             {
-                return false;
+                valid = false;
```
Comment (danil179) [inline GameServerLib/GameObjects/Spell/Missile/SpellMissile.cs]: Similar comments about returning false here.

**Review by danil179 — CHANGES_REQUESTED** [review]
Some comments. The 2 main issues:
1. This function is already kind of blob, so we want to minimize repeated code as much as we can
2. valid can be returned in some cases, which is preferable.

**Comment by lzardy** [comment]
> Some comments. The 2 main issues:
> 
> 1. This function is already kind of blob, so we want to minimize repeated code as much as we can
> 2. valid can be returned in some cases, which is preferable.

All resolved.

**Review by danil179 — APPROVED** [review]
Approved.
