### PR TITLE
Resolve #395 - Fixed spell with empty script cast

### LINKED ISSUE #395: Make spells cast from scripts
There's some spells that aren't cast even when pressed the key (Ex. Kalista E, Yasuo R), script should be able to stop cost/cd from being applied.

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@Furkan_S` in `#game-server`.

### PR DESCRIPTION
**Pull request by danil179**
Spells with empty scripts are now disabled.

### CODE REVIEW

File: GameServerLib/Logic/GameObjects/Spells/Spell.cs [hunk 1]
```diff
@@ -341,5 +344,10 @@ public void LowerCooldown(byte slot, float lowerValue)
         {
             SetCooldown(slot, Owner.Spells[slot].CurrentCooldown - lowerValue);
         }
+
+        public bool IsExist()
```
Comment (MythicManiac) [inline GameServerLib/Logic/GameObjects/Spells/Spell.cs]: This should be a property, and be named more descriptively.

For example:
```CS
public bool HasEmptyScript { get { return spellGameScript.GetType() == typeof(GameScriptEmpty); } }
```

**Review by MythicManiac — CHANGES_REQUESTED** [review]
I don't think this addresses the issue that's referred, but good change nonetheless. Will have to test this before merging, and point to a more proper issue though.

There's also one thing that I'd like to see addressed, but that can also be done as a new issue.

Good work :+1:

**Comment by MythicManiac** [comment]
Code is looking good, I'll have to test the change before I merge now

Nice work :+1:

**Review by MythicManiac — APPROVED** [review]
Seems to be working, merging once CI passes
