### PR TITLE
Resolve #1114, Resolve #1115 -- [Stats] Fix AttackSpeedFlat & Low FPS Particles

### LINKED ISSUE #1114: AttackSpeedFlat hardcoded
Currently AttackSpeedFlat is defined with a hardcoded `0.625f` value (as seen [here](https://github.com/LeagueSandbox/GameServer/blob/indev/GameServerLib/GameObjects/Stats/Stats.cs#L119)), when it should instead be `(1.0f / charData.GlobalCharData.AttackDelay)`.

### LINKED ISSUE #1115: AttackSpeedPerLevel Unused
Currently the character data stat `AttackSpeedPerLevel` is read and setup in Stats, but is never used. This should be implemented in the `LevelUp` function [here](https://github.com/LeagueSandbox/GameServer/blob/indev/GameServerLib/GameObjects/Stats/Stats.cs#L213)
Due to how replication is setup, you will need to use AttackSpeedModifier.

### PR DESCRIPTION
**Pull request by lzardy**
Resolve #1114
Resolve #1115

Credit: Cabeca for bringing AttackSpeedFlat, AttackSpeedPerLevel, and MagicResist issues to my attention.

* ObjAiBase:
  * StopChanneling accounts for no channel spell being active and removes the channel spell otherwise.
* Stats:
  * AttackSpeedFlat is now calculated using GlobalCharData.AttackDelay instead of a hardcoded 0.625f.
  * MagicResist is now calculated correctly per-level.
  * LevelUp now takes into account AttackSpeedPerLevel (and properly shows on the hud).
* Packets:
  * Replaced old usage of HeroSpawn with new S2C_CreateHero.
* Scripting:
  * Moved SummonerHeal particles to HealSpeed buff.
  * SummonerFlash now stops channels.
  * AddParticle/Target now account for low FPS users by defaulting Lifetime to 1 second.

### CODE REVIEW

File: GameServerLib/GameObjects/Stats/Stats.cs [hunk 1]
```diff
@@ -217,11 +218,23 @@ public void LevelUp()
...
+            Armor.BaseValue += ArmorPerLevel;
+            MagicResist.BaseValue += MagicResistPerLevel;
+            HealthRegeneration.BaseValue += HealthRegenerationPerLevel;
+            ManaRegeneration.BaseValue += ManaRegenerationPerLevel;
+
+            if (Level > 1)
+            {
+                AttackSpeedMultiplier = new Stat
+                (
+                    AttackSpeedMultiplier.BaseValue,
```
Comment (danil179) [inline GameServerLib/GameObjects/Stats/Stats.cs]: Why not using StatModifier with only PercentBaseBonus? It will be clearer and more modular.

**Review by danil179 — COMMENTED** [review]
One comment.

**Review by danil179 — APPROVED** [review]
Approved.
