### PR TITLE
Resolve #1135 -- Stacks_and_Renews fix

### LINKED ISSUE #1135: Stacks_and_Renews triggering ActivateBuff incorrectly
Fix Stacks_and_Renews triggering ActivateBuff regardless if MaxStacks was reached or not.

### PR DESCRIPTION
**Pull request by cabeca1143**
Fixed Stacks_and_Renews triggering ActivateBuff regardless if MaxStacks was reached or not.

Resolve #1135

### CODE REVIEW

File: GameServerLib/GameObjects/AttackableUnits/AttackableUnit.cs [hunk 1]
```diff
@@ -721,9 +721,13 @@ public void AddBuff(IBuff b)
                     // Don't need the newly added buff instance as we already have a parent who we can add stacks to.
                     RemoveBuffSlot(b);
 
-                    // Refresh the time of the parent buff and add a stack.
+                    // Refresh the time of the parent buff and adds a stack if Max Stacks wasn't reached.
                     ParentBuffs[b.Name].ResetTimeElapsed();
-                    ParentBuffs[b.Name].IncrementStackCount();
+                    if (ParentBuffs[b.Name].StackCount < ParentBuffs[b.Name].MaxStacks)
```
Comment (danil179) [inline GameServerLib/GameObjects/AttackableUnits/AttackableUnit.cs]: I think that you can simply change the `if` to `if (IncementStackCount)` and remove the Increment... from the inside of the `if` block. The Increment part should already stop at MaxStacks and return false when nothing is added.

**Review by danil179 — CHANGES_REQUESTED** [review]
It is the stack class responsibility for counting the stacks and verifying things.

File: GameServerLib/GameObjects/AttackableUnits/AttackableUnit.cs [hunk 2]
```diff
@@ -721,8 +721,12 @@ public void AddBuff(IBuff b)
                     // Don't need the newly added buff instance as we already have a parent who we can add stacks to.
                     RemoveBuffSlot(b);
 
-                    // Refresh the time of the parent buff and add a stack.
+                    // Refresh the time of the parent buff and adds a stack if Max Stacks wasn't reached.
                     ParentBuffs[b.Name].ResetTimeElapsed();
+
+                    if (ParentBuffs[b.Name].StackCount < ParentBuffs[b.Name].MaxStacks)
```
Comment (lzardy) [inline GameServerLib/GameObjects/AttackableUnits/AttackableUnit.cs]: Make sure to follow the C# guidelines, where all if/else/etc are encased with brackets `{ }` regardless of how small they are.

Comment (cabeca1143) [reply GameServerLib/GameObjects/AttackableUnits/AttackableUnit.cs]: Oh ok, i just thought it would look better without them.
I'll take a look at the guidelines in a bit.

Comment (lzardy) [reply GameServerLib/GameObjects/AttackableUnits/AttackableUnit.cs]: https://github.com/LeagueSandbox/GameServer/blob/indev/CONTRIBUTING.md#c-guidelines

Comment (cabeca1143) [reply GameServerLib/GameObjects/AttackableUnits/AttackableUnit.cs]: Thanks!

**Review by danil179 — CHANGES_REQUESTED** [review]
You can reduce the number of lines as follows:
```
if(ParentBuffs[b.Name].IncrementStackCount())
{
    ParentBuffs[b.Name].ActivateBuff();
}
```
and deleting the line: `ParentBuffs[b.Name].IncrementStackCount();` that goes after the `if`.

**Comment by cabeca1143** [comment]
> You can reduce the number of lines as follows:
> 
> ```
> if(ParentBuffs[b.Name].IncrementStackCount())
> {
>     ParentBuffs[b.Name].ActivateBuff();
> }
> ```
> 
> and deleting the line: `ParentBuffs[b.Name].IncrementStackCount();` that goes after the `if`.

Oh now I see what you mean, PRing the changes rn

**Review by danil179 — APPROVED** [review]
Approved.
