### PR TITLE
Resolve #1191, Resolve #1193 -- Fix Dash & Status Issues

### LINKED ISSUE #1191: Dash Issues
If a status is applied which would prevent movement is applied before a dash, the dash will never be performed, resulting in being unable to move.

Dashes do not entirely ignore collisions between other units.

Forced movements are not networked for units entering vision.

### LINKED ISSUE #1193: Handle Status via Buffs
Status effects (such as Stun, Root, etc.) should be tied to the buffs which applied them so as to remove the need to reapply the status effect each update in case another buff removes it.

### PR DESCRIPTION
**Pull request by lzardy**
Resolve #1191, #1193

* PacketHandler:
  * Forced movements are now properly networked for units entering vision.
* AttackableUnit:
  * Utilized CanMove() before calling Move().
  * Added UpdateStatus function which is used to automatically handle the application of the status effects of buffs.
  * Utilized fixed CanMove for SetWaypoints.
  * OnCollision no longer teleports if the owner or the collider is dashing.
  * Reordered SetStatus to align with StatusFlags enum.
  * Minimized SetDashingState action state applications.
  * Placed DashElapsedTime inside MovementParameters.
* ObjAiBase:
  * Refactored CanMove to better handle priority of checks.
* Buff:
  * Added StatusEffects variable for automatic handling of status flags.
  * Added SetStatusEffect function.
* Scripts:
  * SetStatus now adds each status individually to prevent multi-status flags from being ignored.
  * Utilized Buff.SetStatusEffect.

### CODE REVIEW

File: Content/LeagueSandbox-Scripts/Buffs/Global/Stun.cs [hunk 1]
```diff
@@ -11,25 +11,33 @@ internal class Stun : IBuffGameScript
...
+            SetStatus(unit, StatusFlags.Stunned, false);
             RemoveParticle(stun);
         }
 
         public void OnUpdate(float diff)
         {
-
+            if (owner != null)
+            {
+                SetStatus(owner, StatusFlags.Stunned, true);
```
Comment (danil179) [inline Content/LeagueSandbox-Scripts/Buffs/Global/Stun.cs]: Why is it needed? Shouldn't the unit itself handle if it is stunned by some sort of smart tracking of buffs?

**Review by danil179 — COMMENTED** [review]
Seems fine, but I have a problem with the spamming of stun states. The unit is aware of the buffs activated on itself. If a buff has "stun" property or so, the unit should consider itself stunned. I don't think that sending the stun status every tick is the correct solution. (I understand that if you have 2 stuns, the current solution will remove both when one deactivates, but the problem is more subtle. Different status changes are interfering each other, which could lead to unexpected behavior as part of race conditions).

File: Content/LeagueSandbox-Scripts/Buffs/Global/Stun.cs (hunk 1 above)
Comment (lzardy) [reply Content/LeagueSandbox-Scripts/Buffs/Global/Stun.cs]: The main reason for this was just replicating the functionality of league's scripts.
I don't believe it will cause race conditions as the update loop is a single loop, not multi threaded.

I will change it for now as your suggestion is at least more intuitive.

File: GameServerLib/API/ApiFunctionManager.cs [hunk 2]
```diff
@@ -631,9 +631,22 @@ public static void SetAutocast(ISpell spell)
...
+        /// Sets the state of the given status for the given unit.
+        /// </summary>
+        /// <param name="unit">Unit to set status.</param>
+        /// <param name="status">Status to set.</param>
+        /// <param name="enabled">Whether or not the status should be enabled.</param>
         public static void SetStatus(IAttackableUnit unit, StatusFlags status, bool enabled)
         {
-            unit.SetStatus(status, enabled);
+            // Loop over all possible status flags and set them individually.
+            foreach (StatusFlags enumFlag in Enum.GetValues(typeof(StatusFlags)))
```
Comment (danil179) [inline GameServerLib/API/ApiFunctionManager.cs]: Enum.GetValues is a very slow function. Consider replacing it with something else.

File: GameServerLib/GameObjects/Buff.cs [hunk 3]
```diff
@@ -123,6 +129,24 @@ public IStatsModifier GetStatsModifier()
             return BuffScript.StatsModifier;
         }
 
+        public void SetStatusEffect(StatusFlags flag, bool enabled)
+        {
+            // Loop over all possible status flags and assign them individually to the dictionary
+            foreach (StatusFlags enumFlag in Enum.GetValues(typeof(StatusFlags)))
```
Comment (danil179) [inline GameServerLib/GameObjects/Buff.cs]: Enum.GetValues is a very slow function. Consider replacing it with something else.

File: GameServerLib/GameObjects/AttackableUnits/AttackableUnit.cs [hunk 4]
```diff
@@ -1398,6 +1400,40 @@ public void SetStatus(StatusFlags status, bool enabled)
             }
         }
 
+        public void UpdateStatus()
+        {
+            // Combine the status effects of all the buffs
+            Dictionary<StatusFlags, bool> finalEffects = new Dictionary<StatusFlags, bool>();
+            foreach (IBuff buff in GetBuffs())
```
Comment (danil179) [inline GameServerLib/GameObjects/AttackableUnits/AttackableUnit.cs:1407]: This is in general not very efficient. We should have min priority queue based on the buff duration and its status effects. I'll open an issue and we can implement it later.

**Review by danil179 — APPROVED** [review]
Approved. There are efficiency issues for the future.

File: GameServerLib/API/ApiFunctionManager.cs (hunk 2 above)
Comment (danil179) [reply GameServerLib/API/ApiFunctionManager.cs]: Resolved.
