### PR TITLE
Fix Mana Costs

### LINKED ISSUE #1046: Spell and Projectile Mana Costs
Projectiles spawned by a spell which has a manacost will end up displaying that manacost on the Champion.
Spells that are level 1 do not display mana costs.

### PR DESCRIPTION
**Pull request by lzardy**
* Projectiles will no longer display mana costs due to their replication packet.
* Spells will display their mana costs regardless of level via the CastSpellAns packet.

Resolves #1046

### CODE REVIEW

File: PacketDefinitions420/PacketNotifier.cs [hunk 1]
```diff
@@ -1263,10 +1263,7 @@ public void NotifyMissileReplication(IProjectile p)
             cast.IsClickCasted = false;
 
             cast.SpellSlot = p.OriginSpell != null ? p.OriginSpell.Slot : (byte)0x30;
-            cast.ManaCost = p.OriginSpell != null ? p.OriginSpell.SpellData.ManaCost[p.OriginSpell.Level] : 0f;
             cast.SpellCastLaunchPosition = p.GetPosition3D();
-            cast.AmmoUsed = p.OriginSpell != null ? p.OriginSpell.SpellData.AmmoUsed[p.OriginSpell.Level] : 0;
```
Comment (danil179) [inline PacketDefinitions420/PacketNotifier.cs:1268]: I didn't really understand, why these two lines get removed? Is it related to just the 'display' (which you can change with the tooltips packet)?

File: PacketDefinitions420/PacketNotifier.cs [hunk 2]
```diff
@@ -1665,11 +1662,11 @@ public void NotifyNPC_CastSpellAns(INavigationGrid navGrid, ISpell s, Vector2 st
             };
             if (s.Level > 0)
             {
-                castInfo.ManaCost = s.SpellData.ManaCost[s.Level - 1];
+                castInfo.ManaCost = s.SpellData.ManaCost[s.Level];
             }
             else
             {
-                castInfo.ManaCost = s.SpellData.ManaCost[s.Level];
+                castInfo.ManaCost = s.SpellData.ManaCost[0];
```
Comment (danil179) [inline PacketDefinitions420/PacketNotifier.cs:1669]: in the else case the level can be negative?

**Review by danil179 — APPROVED** [review]
Some comments.

File: PacketDefinitions420/PacketNotifier.cs (hunk 1 above)
Comment (lzardy) [reply PacketDefinitions420/PacketNotifier.cs:1268]: They don't need to be there because it is for a projectile packet.

File: PacketDefinitions420/PacketNotifier.cs (hunk 2 above)
Comment (lzardy) [reply PacketDefinitions420/PacketNotifier.cs:1669]: If it is negative, yes. Unlikely, but just in case.
