### PR TITLE
Resolve #487 -- Implement Stun and fix Silence

### LINKED ISSUE #487: Implement Stun cc type and rework Silence

### PR DESCRIPTION
**Pull request by Deudly**
Implement Stun and fix Silence

Refs #487

### CODE REVIEW

**Review by FurkanS1821 — APPROVED** [review]
Seems cool to me.

File: GameServerLib/Logic/GameObjects/Unit.cs [hunk 1]
```diff
@@ -152,6 +152,8 @@ public Stats GetStats()
 
         public void ApplyCrowdControl(UnitCrowdControl cc)
         {
+            if (cc.IsTypeOf(CrowdControlType.Stun) || cc.IsTypeOf(CrowdControlType.Root))
+                this.StopMovement();
```
Comment (FurkanS1821) [inline GameServerLib/Logic/GameObjects/Unit.cs]: Brackets please.

File: GameServerLib/Logic/Packets/PacketHandlers/Handlers/HandleCastSpell.cs [hunk 2]
```diff
@@ -20,6 +21,8 @@ public bool HandlePacket(Peer peer, byte[] data)
             var owner = _playerManager.GetPeerInfo(peer).Champion;
             if (owner == null)
                 return false;
+            if (!owner.CanCast())
+                return false;
```
Comment (FurkanS1821) [inline GameServerLib/Logic/Packets/PacketHandlers/Handlers/HandleCastSpell.cs]: Brackets for all if conditions here please.

**Review by FurkanS1821 — CHANGES_REQUESTED** [review]

**Review by FurkanS1821 — APPROVED** [review]
