### PR TITLE
Fixed non-damaging targeted projectiles and ranged aa and minion AI (#232 and #233)

### LINKED ISSUE #232: Targeted projectiles (including AA) doesn't deal damage 75% of the time
- [x] Find out which commit caused the bug

Found, 

- [x] Find out which code change caused the bug

Found.

- [X] Fix the code

Fixed

- [X] PR the code

Done.

### PR DESCRIPTION
**Pull request by FurkanS1821**
Close #232 and #233 as this is merged, please.

### CODE REVIEW

File: GameServer/Logic/GameObjects/Unit.cs [hunk 1]
```diff
@@ -603,37 +603,54 @@ public virtual void refreshWaypoints()
...
-
-    1. An enemy champion designated by a call for help from an allied champion. (Enemy champion attacking an Allied champion)
-    2. An enemy minion designated by a call for help from an allied champion. (Enemy minion attacking an Allied champion)
-    3. An enemy minion designated by a call for help from an allied minion. (Enemy minion attacking an Allied minion)
-    4. An enemy turret designated by a call for help from an allied minion. (Enemy turret attacking an Allied minion)
-    5. An enemy champion designated by a call for help from an allied minion. (Enemy champion attacking an Allied minion)
-    6. The closest enemy minion.
-    7. The closest enemy champion.
-*/
+            Under normal circumstances, a minion behavior is simple. Minions follow their attack route until they reach an enemy to engage.
```
Comment (MythicManiac) [inline GameServer/Logic/GameObjects/Unit.cs]: This whole section could very well just be a docstring.

See here: https://msdn.microsoft.com/en-us/library/aa288481(v=vs.71).aspx

File: GameServer/Logic/GameObjects/Unit.cs [hunk 2]
```diff
@@ -650,10 +667,17 @@ public int ClassifyTarget(Unit target)
...
                 return 10;
+            }
+
+            if (target is Champion)
+            {
+                return 11;
+            }
 
-            return 11;
+            return 12;
```
Comment (MythicManiac) [inline GameServer/Logic/GameObjects/Unit.cs]: Instead of returning arbitary values, could we use an enum here?

File: GameServer/Logic/GameObjects/GameObjects.cs [hunk 3]
```diff
@@ -40,7 +40,8 @@ public void SetTeam(TeamId team)
         public int CollisionRadius { get; set; }
         private Vector2 _direction;
         public int VisionRadius { get; private set; }
-        public bool IsDashing { get; private set; }
+        public bool IsDashing { get; protected set; }
+        public bool IsDashingToTarget { get; protected set; }
```
Comment (MythicManiac) [inline GameServer/Logic/GameObjects/GameObjects.cs]: This property to me seems like it's not used anywhere. Is it really necessary?

Also if it is necessary, wouldn't it be smarter to add a `DashTarget` property instead? Now you're just doing `if (IsDashing || IsDashingToTarget)` everywhere, which seems like it could be done simpler.

I'd suggest you to remove the `IsDashingToTarget` property, and use a `DashTarget` property instead. Then if you actually need to check for targetted dashes somewhere, you can check `if (DashTarget != null)`
