### PR TITLE
resolve #999 - crash when handling disconnect by abusing client

### LINKED ISSUE #999: crash when handling disconnect by abusing client
The server crashes when handling a disconnect of already disconnected user.

## Details

This shouldn't happen but it's always better to prevent.

### reproduce
1. start server
2. start client 2 times with the same parameters
3. wait for second client to disconnect (which sends a disconnect packet)
4. disconnect the first client (which sends another packet)

### cause
When handling the second disconnect, the `Find` fails and thus this line throws null reference exception.
https://github.com/LeagueSandbox/GameServer/blob/c7f31b9c362a55d1901245ea78a15e9ad0aaa69a/PacketDefinitions420/PacketHandlerManager.cs#L247

## Fix

Add a null check and log an error if is true.

### PR DESCRIPTION
**Pull request by superewald**
This will fix a hard to reach crash :)

- added null check after find and abort disconnection
- added log message to keep track of this curios event (when this is caused unintentionally it's most likely a severe bug)

Refs #999

### CODE REVIEW

File: PacketDefinitions420/PacketHandlerManager.cs [hunk 1]
```diff
@@ -244,7 +244,13 @@ public bool HandlePacket(Peer peer, byte[] data, Channel channelId)
         public bool HandleDisconnect(Peer peer)
         {
             ulong playerId = _peers.FirstOrDefault(x => x.Value.Address.Equals(peer.Address)).Key;
-            var player = _game.PlayerManager.GetPlayers().Find(x => x.Item2.PlayerId == playerId).Item2;
+            var player = _game.PlayerManager.GetPlayers().Find(x => x.Item2.PlayerId == playerId)?.Item2;
+            if(player == null)
```
Comment (danil179) [inline PacketDefinitions420/PacketHandlerManager.cs]: Add here a space before '('.

**Review by danil179 — APPROVED** [review]
Approved.
